'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getEmployees, type Employee } from '../../lib/api';
import * as api from '../../lib/people-services-api';
import { Badge, Card, Empty, Notice, PageTitle, button, secondary, useAction } from '../leave/ui';
import { Attachments } from './attachments';
export function AnnouncementDetail({ id, admin }: { id: string; admin: boolean }) {
  const [detail, setDetail] = useState<api.AnnouncementDetail | null>(null), [receipt, setReceipt] = useState<api.AnnouncementReceipt | null>(null), [employees, setEmployees] = useState<Employee[]>([]), [loading, setLoading] = useState(true); const action = useAction();
  async function load() { try { if (admin) setDetail(await api.getAnnouncementDetail(id)); else setReceipt(await api.getAnnouncementReceipt(id)); } finally { setLoading(false); } }
  useEffect(() => { setDetail(null); setReceipt(null); setLoading(true); void action.run(load); if (admin) void getEmployees().then(setEmployees).catch(() => {}); }, [id, admin]);
  const item = admin ? detail : receipt?.announcement;
  return <div className="space-y-6"><PageTitle eyebrow="Employee services" title={item?.title ?? 'Announcement details'} text={admin ? 'Announcement administration, recipient tracking, attachments and communication history.' : 'Read the announcement, download supporting documents and record your acknowledgement.'}/><div className="flex gap-2"><Link className={secondary} href="/communications">Back to Communications</Link><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh</button></div><Notice error={action.error} message={action.message}/>{loading ? <Empty>Loading announcement…</Empty> : item && <>
  <Card title={item.title}><div className="flex flex-wrap gap-2"><Badge value={api.announcementState(item)}/>{item.pinned && <Badge value="PINNED"/>}{item.important && <Badge value="IMPORTANT"/>}{!admin && receipt && <Badge value={receipt.readAt ? 'READ' : 'UNREAD'}/>}</div><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{item.body}</p><p className="text-xs text-slate-500">Published {api.dateTimeLabel(item.publishedAt)}{item.expiresAt ? ` · Expires ${api.dateTimeLabel(item.expiresAt)}` : ''}</p>{item.requiresAcknowledgement && <p className="text-sm font-medium text-indigo-700">Employee acknowledgement required.</p>}
  {!admin && receipt && <div className="space-y-3"><div className="flex flex-wrap gap-2">{!receipt.readAt && <button disabled={action.busy} className={secondary} onClick={() => void action.run(async () => { await api.markAnnouncementRead(id); await load(); }, 'Announcement marked as read.')}>Mark as read</button>}{item.requiresAcknowledgement && !receipt.acknowledgedAt && <button disabled={action.busy} className={button} onClick={() => void action.run(async () => { await api.acknowledgeAnnouncement(id); await load(); }, 'Acknowledgement recorded.')}>I acknowledge this announcement</button>}</div>{receipt.readAt && <p className="text-xs text-slate-500">Read {api.dateTimeLabel(receipt.readAt)}</p>}{receipt.acknowledgedAt && <p className="text-sm text-emerald-700">Acknowledged {api.dateTimeLabel(receipt.acknowledgedAt)}</p>}</div>}
  {admin && <><p className="break-all text-sm text-slate-500">Audience: {item.audience}{item.departmentId ? ` · Department ${item.departmentId}` : item.workLocationId ? ` · Location ${item.workLocationId}` : item.teamId ? ` · Team ${item.teamId}` : ''}</p><button disabled={action.busy} className={secondary} onClick={() => { if (window.confirm(`${item.isActive ? 'Deactivate' : 'Activate'} this announcement? Employee visibility also depends on its publication and expiry dates.`)) void action.run(async () => { await api.setAnnouncementActive(id, !item.isActive); await load(); }, 'Announcement state updated.'); }}>{item.isActive ? 'Deactivate announcement' : 'Activate announcement'}</button></>}
  </Card>
  <Attachments items={item.attachments} path={api.announcementFilePath(id, admin)} canUpload={admin && item.isActive} onSaved={load}/>
  {admin && detail && <><Card title="Recipient read & acknowledgement tracking"><div className="grid gap-4 sm:grid-cols-3">{[['Recipients', detail.recipients.length], ['Read', detail.recipients.filter(r => r.readAt).length], ['Acknowledged', detail.requiresAcknowledgement ? detail.recipients.filter(r => r.acknowledgedAt).length : 'Not required']].map(([title, count]) => <div key={String(title)} className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{title}</p><p className="mt-1 text-2xl font-semibold">{count}</p></div>)}</div><p className="text-sm text-slate-500">Recipients were selected when this announcement was created.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200"><th className="p-3">Employee</th><th className="p-3">Read</th><th className="p-3">Acknowledgement</th></tr></thead><tbody>{detail.recipients.map(r => { const e = employees.find(e => e.id === r.employeeId); return <tr key={r.employeeId} className="border-b border-slate-100"><td className="max-w-xs break-all p-3">{e ? `${e.firstName} ${e.lastName}` : r.employeeId}</td><td className="p-3">{r.readAt ? api.dateTimeLabel(r.readAt) : 'Unread'}</td><td className="p-3">{r.acknowledgedAt ? api.dateTimeLabel(r.acknowledgedAt) : detail.requiresAcknowledgement ? 'Pending' : 'Not required'}</td></tr>; })}</tbody></table></div></Card><Card title="Communication history">{!detail.events.length ? <Empty>No history recorded.</Empty> : detail.events.map(event => <div key={event.id} className="space-y-2 rounded-xl border border-slate-200 p-4"><p className="text-sm font-medium">{event.type.replaceAll('_', ' ')}</p><p className="break-all text-xs text-slate-500">{api.dateTimeLabel(event.createdAt)} · {event.actorUserId}</p></div>)}</Card></>}
  </>}</div>;
}
