'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getCompanyUsers, type CompanyUser } from '../../lib/api';
import * as api from '../../lib/people-services-api';
import { Badge, Card, Empty, Field, Notice, PageTitle, button, control, secondary, text, useAction } from '../leave/ui';
import { Attachments } from './attachments';
import { Sla } from './sla';
export function HrRequestDetail({ id, admin }: { id: string; admin: boolean }) {
  const [request, setRequest] = useState<api.HrDetail | null>(null), [users, setUsers] = useState<CompanyUser[]>([]), [loading, setLoading] = useState(true);
  const action = useAction();
  async function load() { try { setRequest(await api.getHrDetail(id, admin)); } finally { setLoading(false); } }
  useEffect(() => { setRequest(null); setLoading(true); void action.run(load); if (admin) void getCompanyUsers().then(data => setUsers(data.filter(u => ['HR_ADMIN', 'COMPANY_ADMIN'].includes(u.role)))).catch(() => {}); }, [id, admin]);
  const assignee = request?.assignedToUserId ? users.find(u => u.id === request.assignedToUserId)?.fullName ?? request.assignedToUserId : 'Unassigned';
  return <div className="space-y-6"><PageTitle eyebrow="Employee services" title={request?.reference ?? 'HR request details'} text={admin ? 'HR administration: assignment, priorities, escalation, internal notes and service history.' : 'Follow your request, send comments and share supporting documents.'}/><div className="flex gap-2"><Link className={secondary} href="/hr-service-desk">Back to Service Desk</Link><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh</button></div><Notice error={action.error} message={action.message}/>{loading ? <Empty>Loading request…</Empty> : request && <>
  <Card title="Request summary"><div className="flex flex-wrap gap-2"><Badge value={request.status}/><Badge value={request.priority}/></div><p className="whitespace-pre-wrap text-sm">{request.summary}</p><p className="text-sm text-slate-500">Category: {request.category} · Created {api.dateTimeLabel(request.createdAt)}</p><p className="break-all text-xs text-slate-500">Employee: {request.employeeId} · Assigned to: {assignee} · Escalation level {request.escalationLevel}</p><Sla request={request}/>{request.closedAt && <p className="text-xs text-slate-500">Closed {api.dateTimeLabel(request.closedAt)}</p>}</Card>
  {admin && <Card title="HR controls"><div className="grid gap-6 md:grid-cols-2"><form className="space-y-3" onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); void action.run(async () => { await api.assignHrRequest(id, text(d, 'userId')); await load(); }, 'Request assigned.'); }}><Field label="Assign to HR / company administrator"><select key={request.assignedToUserId ?? 'unassigned'} name="userId" required className={control} defaultValue={request.assignedToUserId ?? ''}><option value="">Select user</option>{users.map(u => <option key={u.id} value={u.id}>{u.fullName}{u.isActive ? '' : ' (inactive)'}</option>)}</select></Field><button disabled={action.busy || request.status === 'CLOSED'} className={button}>Assign</button></form>
  <form className="space-y-3" onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); void action.run(async () => { await api.changeHrPriority(id, text(d, 'priority') as api.HrPriority); await load(); }, 'Priority updated.'); }}><Field label="Priority"><select key={request.priority} name="priority" className={control} defaultValue={request.priority}>{['LOW', 'NORMAL', 'HIGH', 'URGENT'].map(p => <option key={p}>{p}</option>)}</select></Field><button disabled={action.busy} className={button}>Update priority</button></form>
  <form key={request.status} className="space-y-3" onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); const status = text(d, 'status') as api.HrStatus; if (status === 'CLOSED' && !window.confirm('Close this resolved request? Closed requests cannot be reopened through this API.')) return; void action.run(async () => { await api.changeHrStatus(id, status); await load(); }, 'Status updated.'); }}><Field label="Next status"><select name="status" required className={control} disabled={!api.hrTransitions[request.status].length}>{!api.hrTransitions[request.status].length ? <option value="">No further transitions</option> : api.hrTransitions[request.status].map(s => <option key={s}>{s}</option>)}</select></Field><button disabled={action.busy || !api.hrTransitions[request.status].length} className={button}>Change status</button></form>
  <form className="space-y-3" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => { const reason = text(d, 'reason'); if (reason.length < 5) throw new Error('Escalation requires a reason of at least five characters.'); await api.escalateHrRequest(id, text(d, 'userId'), reason); await load(); form.reset(); }, 'Request escalated.'); }}><Field label="Escalate to"><select name="userId" required className={control}><option value="">Select user</option>{users.map(u => <option key={u.id} value={u.id}>{u.fullName}</option>)}</select></Field><Field label="Escalation reason"><textarea name="reason" required minLength={5} maxLength={500} className={control}/></Field><button disabled={action.busy || request.status === 'CLOSED'} className={button}>Escalate</button></form></div></Card>}
  <div className="grid gap-6 xl:grid-cols-2"><Card title={admin ? 'Comments & internal HR notes' : 'Conversation'}>{!request.comments.length ? <Empty>No comments yet.</Empty> : request.comments.map(c => <div key={c.id} className="space-y-2 rounded-xl border border-slate-200 p-4"><Badge value={c.internal ? 'INTERNAL HR NOTE' : 'COMMENT'}/><p className="whitespace-pre-wrap text-sm">{c.body}</p><p className="break-all text-xs text-slate-500">{api.dateTimeLabel(c.createdAt)} · {users.find(u => u.id === c.actorUserId)?.fullName ?? c.actorUserId}</p></div>)}{request.status !== 'CLOSED' ? <form className="space-y-3" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => { const body = text(d, 'body'); if (body.length < 2) throw new Error('Enter a comment of at least two characters.'); await api.addHrComment(id, admin, body, admin && d.has('internal')); await load(); form.reset(); }, 'Comment recorded.'); }}><fieldset disabled={action.busy} className="space-y-3"><Field label="Comment"><textarea name="body" required minLength={2} maxLength={3000} className={control}/></Field>{admin && <label className="flex items-center gap-2 text-sm"><input name="internal" type="checkbox"/>Internal HR note (hidden from employee)</label>}<button className={button}>Add comment</button></fieldset></form> : <p className="text-sm text-slate-500">This request is closed; comments are disabled.</p>}</Card>
  <Attachments items={request.attachments} path={`${api.hrDetailPath(id, admin)}/attachments`} canUpload={request.status !== 'CLOSED'} internal={admin} onSaved={load}/></div>
  <Card title="Request history">{request.events.map(event => <div key={event.id} className="space-y-2 rounded-xl border border-slate-200 p-4"><p className="text-sm font-medium">{event.type.replaceAll('_', ' ')}</p>{event.detail && <p className="whitespace-pre-wrap text-sm text-slate-600">{event.detail}</p>}<p className="break-all text-xs text-slate-500">{api.dateTimeLabel(event.createdAt)} · {event.actorUserId}</p></div>)}</Card>
  </>}</div>;
}
