'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { usePlatformIdentity } from '../../../components/platform-admin/platform-shell';
import { button, secondary, Notice } from '../../../components/leave/ui';
import { treasuryWorkspace, treasuryEligible, treasuryDetail, treasuryFundingCreate, treasuryFundingAction, treasuryFundingInspect, treasuryPrepare, treasuryAction, treasuryInspect, treasuryResult, treasuryDownload, type TreasuryWorkspace, type TreasuryEligible, type TreasuryBatch, type TreasuryInspection } from '../../../lib/early-pay-treasury-api';
const input='w-full rounded-lg border border-slate-300 bg-white p-2 text-sm';
const card='space-y-4 rounded-2xl border border-slate-200 bg-white p-5';
const money=(cents:number)=>(cents/100).toLocaleString('en-ZA',{style:'currency',currency:'ZAR'});
type Action={kind:'funding-review'|'funding-inspect'|'funding-retire'|'approve'|'cancel'|'submit'|'inspect'|'result';id:string;itemId?:string;decision?:'APPROVED'|'REJECTED'};
export default function TreasuryPage() {
  const identity=usePlatformIdentity();
  const [data,setData]=useState<TreasuryWorkspace|null>(null),[eligible,setEligible]=useState<TreasuryEligible[]>([]),[batch,setBatch]=useState<TreasuryBatch|null>(null),[selected,setSelected]=useState<string[]>([]),[funding,setFunding]=useState(''),[date,setDate]=useState(''),[prepareReason,setPrepareReason]=useState('');
  const [tab,setTab]=useState<'payouts'|'funding'>('payouts'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[action,setAction]=useState<Action|null>(null),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[bankReference,setBankReference]=useState(''),[evidence,setEvidence]=useState(''),[outcome,setOutcome]=useState('PAID'),[inspection,setInspection]=useState<TreasuryInspection|null>(null),[fundingInspection,setFundingInspection]=useState<{id:string;accountNumber:string}|null>(null);
  const selectionVersion=useRef(0),mounted=useRef(true);
  const [newFunding,setNewFunding]=useState({name:'',adapterId:'',accountHolder:'',accountNumber:'',branchCode:'',accountType:'CURRENT',ownReference:'DELUXHR EP',reason:''});
  function hideSensitive(){setInspection(null);setFundingInspection(null);setPassword('');setNewFunding(s=>({...s,accountNumber:''}));}
  async function refresh(key?:string){hideSensitive();const [w,e]=await Promise.all([treasuryWorkspace(),treasuryEligible()]);if(!mounted.current)return;setData(w);setEligible(e);setSelected(s=>s.filter(k=>e.some(r=>r.id===k)));if(key)setBatch(await treasuryDetail(key));}
  useEffect(()=>{mounted.current=true;void refresh().catch(e=>setError(e instanceof Error?e.message:'Unable to load treasury.'));return()=>{mounted.current=false;selectionVersion.current++;};},[]);
  useEffect(()=>{function blur(){hideSensitive();selectionVersion.current++;}window.addEventListener('blur',blur);return()=>window.removeEventListener('blur',blur);},[]);
  useEffect(()=>{if(action)document.getElementById('treasury-action')?.scrollIntoView({behavior:'smooth',block:'start'});},[action]);
  async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Treasury operation failed.');}finally{setBusy(false);setPassword('');}}
  function open(a:Action){selectionVersion.current++;hideSensitive();setAction(a);setReason('');setBankReference('');setEvidence('');setOutcome('PAID');}
  async function choose(key:string){const version=++selectionVersion.current;hideSensitive();setAction(null);await run(async()=>{const b=await treasuryDetail(key);if(version===selectionVersion.current)setBatch(b);});}
  async function create(e:FormEvent){e.preventDefault();const payload={...newFunding};await run(async()=>{try{await treasuryFundingCreate(payload);await refresh();setMessage('Funding account submitted for independent review.');}finally{setNewFunding(s=>({...s,accountNumber:''}));}});}
  async function prepare(e:FormEvent){e.preventDefault();await run(async()=>{const b=await treasuryPrepare({fundingAccountId:funding,paymentDate:date,requestIds:selected,reason:prepareReason});setBatch(b);setSelected([]);setPrepareReason('');await refresh(b.id);setMessage('Payout batch prepared. A different platform administrator must approve release.');});}
  async function execute(e:FormEvent){e.preventDefault();if(!action)return;const a=action,version=selectionVersion.current,payload={password,reason};setPassword('');await run(async()=>{
    if(a.kind==='funding-inspect'){const result=await treasuryFundingInspect(a.id,payload);if(version===selectionVersion.current&&mounted.current)setFundingInspection(result);setAction(null);return;}
    if(a.kind==='inspect'){const result=await treasuryInspect(a.id,payload);if(version===selectionVersion.current&&mounted.current)setInspection(result);setAction(null);return;}
    if(a.kind==='funding-review')await treasuryFundingAction(a.id,'review',{...payload,decision:a.decision!});
    else if(a.kind==='funding-retire')await treasuryFundingAction(a.id,'retire',payload);
    else if(a.kind==='result')await treasuryResult(a.id,a.itemId!,{...payload,outcome,bankReference,evidence});
    else await treasuryAction(a.id,a.kind,a.kind==='submit'?{...payload,bankReference,evidence,method:'MANUAL_BANK_PORTAL'}:payload);
    setAction(null);await refresh(batch?.id);setMessage('Treasury action recorded.');
  });}
  const released=batch&&['APPROVED','SUBMITTED','RECONCILED'].includes(batch.status);
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Early Pay treasury</h1><p className="text-sm text-slate-500">Platform funding, independent release and bank-result reconciliation.</p></div><button className={secondary} disabled={busy} onClick={()=>void run(()=>refresh(batch?.id))}>Refresh</button></div>
    <Notice error={error} message={message}/><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Production bank files are awaiting bank validation. Reports and FNB drafts must not be uploaded for payment. Manual bank-portal payments can be recorded separately; only independent confirmation of bank evidence marks a request paid. Instant requests still depend on the bank product used.</div>
    <div className="flex gap-2">{(['payouts','funding'] as const).map(t=><button key={t} className={tab===t?button:secondary} onClick={()=>{hideSensitive();setAction(null);selectionVersion.current++;setTab(t);}}>{t==='payouts'?'Payout batches':'Funding accounts'}</button>)}</div>
    {!data&&<p>Loading treasury…</p>}
    {data&&tab==='funding'&&<><form className={card} onSubmit={create}><h2 className="font-semibold">Add a platform funding account</h2><p className="text-sm text-slate-500">Company accounts are configured separately. Account details are immutable after submission.</p><div className="grid gap-3 md:grid-cols-2">{(['name','accountHolder','accountNumber','branchCode','ownReference'] as const).map(k=><label key={k} className="text-sm">{({name:'Account label',accountHolder:'Account holder',accountNumber:'Account number',branchCode:'Branch code',ownReference:'Own reference'})[k]}<input className={input} required maxLength={k==='accountNumber'?20:k==='branchCode'?6:k==='ownReference'?20:k==='name'?80:100} minLength={k==='accountNumber'?6:k==='branchCode'?6:1} pattern={k==='accountNumber'?'[0-9]{6,20}':k==='branchCode'?'[0-9]{6}':undefined} value={newFunding[k]} onChange={e=>setNewFunding(s=>({...s,[k]:e.target.value}))}/></label>)}<label className="text-sm">Banking product<select required className={input} value={newFunding.adapterId} onChange={e=>setNewFunding(s=>({...s,adapterId:e.target.value}))}><option value="">Select a bank and product</option>{data.adapters.map(a=><option key={a.id} value={a.id}>{a.bank} · {a.channel} · {a.id}</option>)}</select></label><label className="text-sm">Account type<select className={input} value={newFunding.accountType} onChange={e=>setNewFunding(s=>({...s,accountType:e.target.value}))}>{['CURRENT','SAVINGS','TRANSMISSION'].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-sm">Reason<input required minLength={3} maxLength={500} className={input} value={newFunding.reason} onChange={e=>setNewFunding(s=>({...s,reason:e.target.value}))}/></label></div><button disabled={busy} className={button}>Submit for review</button></form>
    <section className={card}><h2 className="font-semibold">Platform funding accounts</h2>{data.accounts.length===0&&<p className="text-sm text-slate-500">No funding accounts configured.</p>}{data.accounts.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-t pt-3"><div><p className="font-medium">{p.name} · {p.bank}</p><p className="text-sm text-slate-500">{p.accountHolder} · {p.accountNumberMasked} · {p.branchCode} · {p.status}</p>{fundingInspection?.id===p.id&&<div className="mt-2 rounded bg-amber-50 p-2 text-sm">Account: {fundingInspection.accountNumber} <button className={secondary} onClick={hideSensitive}>Hide account</button></div>}</div><div className="flex flex-wrap gap-2">{p.status==='PENDING_APPROVAL'&&p.createdBy!==identity?.id&&<><button className={secondary} disabled={busy} onClick={()=>open({kind:'funding-inspect',id:p.id})}>Inspect</button><button className={button} disabled={busy} onClick={()=>open({kind:'funding-review',id:p.id,decision:'APPROVED'})}>Approve</button><button className={secondary} disabled={busy} onClick={()=>open({kind:'funding-review',id:p.id,decision:'REJECTED'})}>Reject</button></>}{p.status==='APPROVED'&&<button className={secondary} disabled={busy} onClick={()=>open({kind:'funding-retire',id:p.id})}>Retire</button>}</div></div>)}</section></>}
    {data&&tab==='payouts'&&<><form className={card} onSubmit={prepare}><h2 className="font-semibold">Prepare approved requests</h2><div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Funding account<select required className={input} value={funding} onChange={e=>setFunding(e.target.value)}><option value="">Choose approved funding</option>{data.accounts.filter(p=>p.status==='APPROVED').map(p=><option key={p.id} value={p.id}>{p.name} · {p.accountNumberMasked}</option>)}</select></label><label className="text-sm">Payment date<input type="date" required className={input} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="text-sm">Reason<input required minLength={3} maxLength={500} className={input} value={prepareReason} onChange={e=>setPrepareReason(e.target.value)}/></label></div><div className="max-h-72 overflow-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Select','Company / employee','Amount','Transfer'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{eligible.map(r=><tr key={r.id} className="border-t"><td className="p-3"><input type="checkbox" aria-label={`Select ${r.employee.firstName} ${r.employee.lastName}`} checked={selected.includes(r.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.id]:s.filter(k=>k!==r.id))}/></td><td className="p-3">{r.organization.name}<p className="text-slate-500">{r.employee.firstName} {r.employee.lastName} · {r.employee.employeeNumber}</p></td><td className="p-3">{money(Math.round(r.netDisbursement*100))}</td><td className="p-3">{r.transferType}</td></tr>)}</tbody></table>{!eligible.length&&<p className="p-4 text-sm text-slate-500">No unallocated approved requests. Preparation also checks company services and approved bank details.</p>}</div><div className="flex flex-wrap items-center gap-3"><button className={button} disabled={busy||!selected.length}>Prepare {selected.length} request(s)</button><span className="text-sm text-slate-500">{money(eligible.filter(r=>selected.includes(r.id)).reduce((n,r)=>n+Math.round(r.netDisbursement*100),0))}</span></div></form>
    <section className={card}><h2 className="font-semibold">Payout batches</h2><label className="block text-sm">Select batch<select className={input} value={batch?.id??''} disabled={busy} onChange={e=>void choose(e.target.value)}><option value="" disabled>Select a batch</option>{data.batches.map(b=><option key={b.id} value={b.id}>{b.id.slice(0,8)} · {b.status} · {money(b.totalCents)} · {b._count?.items} items</option>)}</select></label>
    {batch&&<><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{batch.status} · {money(batch.totalCents)}</p><p className="text-sm text-slate-500">{batch.funding.name} · {batch.funding.bank} · {batch.funding.accountNumberMasked} · {batch.paymentDate.slice(0,10)}</p><p className="text-xs text-slate-400 break-all">{batch.id}</p></div><div className="flex flex-wrap gap-2">{batch.status==='PREPARED'&&batch.preparedBy!==identity?.id&&<button disabled={busy} className={button} onClick={()=>open({kind:'approve',id:batch.id})}>Approve release</button>}{['PREPARED','APPROVED'].includes(batch.status)&&<button disabled={busy} className={secondary} onClick={()=>open({kind:'cancel',id:batch.id})}>Cancel batch</button>}{batch.status==='APPROVED'&&<button disabled={busy} className={button} onClick={()=>open({kind:'submit',id:batch.id})}>Record manual bank submission</button>}{['APPROVED','SUBMITTED'].includes(batch.status)&&<button disabled={busy} className={secondary} onClick={()=>open({kind:'inspect',id:batch.id})}>Inspect payment details</button>}{released&&<button disabled={busy} className={secondary} onClick={()=>void run(()=>treasuryDownload(batch.id))}>Download masked report</button>}{released&&batch.funding.adapterId==='FNB_OBE_BANKSERV'&&<button disabled={busy} className={secondary} onClick={()=>{hideSensitive();void run(()=>treasuryDownload(batch.id,true));}}>Download FNB test draft</button>}</div></div>
    {inspection&&<div className="rounded-xl bg-amber-50 p-3 text-sm"><div className="flex justify-between gap-3"><p>Funding account: {inspection.funding.accountNumber} · branch {inspection.funding.branchCode}</p><button className={secondary} onClick={hideSensitive}>Hide payment details</button></div><p className="mt-2 text-xs">Visible only during this session. Details are hidden on refresh, navigation and window blur.</p></div>}
    {batch.submissionReference&&<p className="text-sm text-slate-600">Bank submission: {batch.submissionReference} · {batch.submissionEvidence}</p>}
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Employee / beneficiary','Amount','Payment reference','Bank result','Action'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{batch.items.map(i=><tr className="border-t" key={i.id}><td className="p-3">{i.employeeName}<p className="text-xs text-slate-500">{i.beneficiary.accountHolderName} · {i.beneficiary.bankName} · {i.beneficiary.accountNumberMasked} · {i.beneficiary.transferType}</p>{inspection&&<p className="text-xs text-amber-800">Account: {inspection.items.find(r=>r.id===i.id)?.beneficiary.accountNumber} · {i.beneficiary.branchCode} · {i.beneficiary.accountType}</p>}</td><td className="p-3">{money(i.amountCents)}</td><td className="p-3">{i.paymentReference}</td><td className="p-3">{i.status}{i.bankReference&&<p className="text-xs text-slate-500">{i.bankReference}</p>}</td><td className="p-3">{batch.status==='SUBMITTED'&&i.status==='PENDING'&&identity?.id!==batch.submittedBy&&identity?.id!==batch.preparedBy&&<button className={secondary} disabled={busy} onClick={()=>open({kind:'result',id:batch.id,itemId:i.id})}>Confirm bank result</button>}{i.status==='FAILED'&&<span className="text-xs text-amber-700">Held for recovery; no automatic retry</span>}</td></tr>)}</tbody></table></div></>}
    </section></>}
    {action&&<form id="treasury-action" className={card} onSubmit={execute}><div className="flex justify-between"><h2 className="font-semibold">{action.kind==='funding-review'?`${action.decision==='APPROVED'?'Approve':'Reject'} funding account`:action.kind.replaceAll('-',' ')}</h2><button type="button" className={secondary} disabled={busy} onClick={()=>{selectionVersion.current++;hideSensitive();setAction(null);}}>Close</button></div>
      {action.kind==='submit'&&<p className="text-sm text-amber-900">Record only payments already submitted manually in the bank portal against these frozen instructions. This action does not send money. Do not upload a report or test draft.</p>}
      {action.kind==='result'&&<><p className="text-sm text-amber-900">Confirm the final bank outcome from settlement evidence. A paid result enables payroll recovery. Accepted or pending instructions are not final paid results.</p><label className="block text-sm">Final outcome<select className={input} value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="PAID">Paid / settled</option><option value="FAILED">Failed / rejected</option></select></label></>}
      {['submit','result'].includes(action.kind)&&<><label className="block text-sm">Bank reference<input required minLength={3} maxLength={100} className={input} value={bankReference} onChange={e=>setBankReference(e.target.value)}/></label><label className="block text-sm">Bank evidence reference / description<textarea required minLength={10} maxLength={1000} className={input} value={evidence} onChange={e=>setEvidence(e.target.value)}/><span className="text-xs text-slate-500">Use a traceable bank confirmation reference. Do not include passwords or access tokens.</span></label></>}
      <label className="block text-sm">Audit reason<textarea required minLength={3} maxLength={500} className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="block text-sm">Your password<input required type="password" autoComplete="current-password" maxLength={200} className={input} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className={button} disabled={busy}>Confirm action</button></form>}
  </div>;
}
