'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getCompanyUsers, type CompanyUser } from '../../lib/api';
import * as api from '../../lib/people-services-api';
import { Badge, Card, Empty, Field, Notice, PageTitle, button, control, number, secondary, text, useAction } from '../../components/leave/ui';
import { Sla } from '../../components/people-services/sla';
type Tab = 'My requests' | 'HR queue' | 'Categories' | 'Reporting';
export default function HrServiceDeskPage() {
  const [tab, setTab] = useState<Tab>('My requests');
  return <div className="space-y-6"><PageTitle eyebrow="Employee services" title="HR Service Desk" text="Send requests to HR, follow responses, and manage the company support queue."/><div className="flex flex-wrap gap-2">{(['My requests', 'HR queue', 'Categories', 'Reporting'] as Tab[]).map(t => <button key={t} className={tab === t ? button : secondary} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === 'My requests' ? <MyRequests/> : tab === 'HR queue' ? <HrQueue/> : tab === 'Categories' ? <Categories/> : <Reporting/>}</div>;
}
function RequestList({ items, admin }: { items: api.HrRequest[]; admin: boolean }) {
  return !items.length ? <Empty>No requests in this view.</Empty> : <div className="space-y-3">{items.map(r => <article key={r.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><Link className="font-semibold text-indigo-700 underline" href={`/hr-service-desk/${admin ? 'admin/' : ''}${encodeURIComponent(r.id)}`}>{r.reference}</Link><div className="flex gap-2"><Badge value={r.status}/><Badge value={r.priority}/></div></div><p className="whitespace-pre-wrap text-sm">{r.summary}</p><p className="text-xs text-slate-500">{r.category} · Created {api.dateTimeLabel(r.createdAt)} · Escalation {r.escalationLevel}</p><Sla request={r}/></article>)}</div>;
}
function MyRequests() {
  const [items, setItems] = useState<api.HrRequest[]>([]), [categories, setCategories] = useState<api.HrCategory[]>([]), [loading, setLoading] = useState(true);
  const action = useAction();
  async function load() {
    const results = await Promise.allSettled([api.getMyHrRequests(), api.getHrCategories()]);
    if (results[0].status === 'fulfilled') setItems(results[0].value);
    if (results[1].status === 'fulfilled') setCategories(results[1].value);
    setLoading(false); const failed = results.find(r => r.status === 'rejected'); if (failed?.status === 'rejected') throw failed.reason;
  }
  useEffect(() => { void action.run(load); }, []);
  return <div className="space-y-6"><Notice error={action.error} message={action.message}/><div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]"><Card title="New employee request"><p className="text-sm text-slate-500">Requests are submitted for your linked employee account. An administrator account without an employee link can use the HR queue.</p><form className="space-y-4" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, data = new FormData(form); void action.run(async () => { const summary = text(data, 'summary'); if (summary.length < 5) throw new Error('Enter at least five characters.'); const created = await api.createHrRequest(summary, text(data, 'categoryId')); setItems(old => [created, ...old]); form.reset(); }, 'HR request created. Open it to add comments and attachments.'); }}><fieldset disabled={action.busy} className="space-y-4"><Field label="Category"><select name="categoryId" className={control}><option value="">General</option>{categories.filter(c => c.isActive).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="How can HR help?"><textarea name="summary" minLength={5} maxLength={500} required className={control}/></Field><button className={button}>Submit request</button></fieldset></form></Card><Card title="My requests"><p className="text-sm text-slate-500">Latest 100 requests for your account.</p><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh</button>{loading ? <Empty>Loading your requests…</Empty> : <RequestList items={items} admin={false}/>}</Card></div></div>;
}
function HrQueue() {
  const [items, setItems] = useState<api.HrRequest[]>([]), [categories, setCategories] = useState<api.HrCategory[]>([]), [users, setUsers] = useState<CompanyUser[]>([]), [loading, setLoading] = useState(true);
  const action = useAction();
  async function load(filters: api.HrFilters = {}) { try { setItems(await api.getHrQueue(filters)); } finally { setLoading(false); } }
  useEffect(() => { void action.run(() => load()); void api.getHrCategories().then(setCategories).catch(() => {}); void getCompanyUsers().then(setUsers).catch(() => {}); }, []);
  return <Card title="Company HR queue"><Notice error={action.error} message={action.message}/><p className="text-sm text-slate-500">Up to 200 oldest matching requests. Apply filters to narrow the queue. HR queue access requires the corresponding permission.</p><form className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5" onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); void action.run(() => load({ ...(text(d, 'status') ? { status: text(d, 'status') as api.HrStatus } : {}), ...(text(d, 'priority') ? { priority: text(d, 'priority') as api.HrPriority } : {}), ...(text(d, 'assignee') ? { assignee: text(d, 'assignee') } : {}), ...(text(d, 'categoryId') ? { categoryId: text(d, 'categoryId') } : {}), ...(d.has('overdue') ? { overdue: 'true' } : {}) })); }}>
    <Field label="Status"><select name="status" className={control}><option value="">All statuses</option>{Object.keys(api.hrTransitions).map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Priority"><select name="priority" className={control}><option value="">All priorities</option>{['LOW', 'NORMAL', 'HIGH', 'URGENT'].map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Category"><select name="categoryId" className={control}><option value="">All categories</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Assigned user"><select name="assignee" className={control}><option value="">All assignees</option>{users.filter(u => ['HR_ADMIN', 'COMPANY_ADMIN'].includes(u.role)).map(u => <option key={u.id} value={u.id}>{u.fullName}</option>)}</select></Field><div className="flex flex-col justify-end gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="overdue"/>Overdue only</label><button disabled={action.busy} className={button}>Apply / refresh</button></div></form><p className="text-xs text-slate-500">Overdue matches the API queue definition; historical SLA breaches are reported separately.</p>{loading ? <Empty>Loading company queue…</Empty> : <><p className="text-sm text-slate-500">{items.length} requests shown</p><RequestList items={items} admin/></>}</Card>;
}
function Categories() {
  const [items, setItems] = useState<api.HrCategory[]>([]), [editing, setEditing] = useState<api.HrCategory | null>(null); const action = useAction();
  async function load() { setItems(await api.getHrCategories()); }
  useEffect(() => { void action.run(load); }, []);
  return <div className="space-y-6"><Notice error={action.error} message={action.message}/><div className="grid gap-6 xl:grid-cols-2"><Card title={editing ? 'Update category' : 'Create category'}><p className="text-sm text-slate-500">The category code identifies an existing category. SLA changes apply to future requests.</p><form key={editing?.id ?? 'new'} className="space-y-4" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => { const response = number(d, 'response'), resolution = number(d, 'resolution'); if (response > resolution) throw new Error('Response SLA cannot exceed resolution SLA.'); await api.saveHrCategory({ code: text(d, 'code').toUpperCase(), name: text(d, 'name'), responseSlaHours: response, resolutionSlaHours: resolution, isActive: d.has('active') }); await load(); setEditing(null); form.reset(); }, 'Category saved.'); }}><fieldset disabled={action.busy} className="space-y-4"><Field label="Code"><input name="code" required pattern="[A-Za-z][A-Za-z0-9_]{1,31}" maxLength={32} readOnly={!!editing} defaultValue={editing?.code ?? ''} className={control}/></Field><Field label="Name"><input name="name" required minLength={2} maxLength={100} defaultValue={editing?.name ?? ''} className={control}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Response SLA (hours)"><input name="response" type="number" required min={1} max={8760} step={1} defaultValue={editing?.responseSlaHours ?? 24} className={control}/></Field><Field label="Resolution SLA (hours)"><input name="resolution" type="number" required min={1} max={8760} step={1} defaultValue={editing?.resolutionSlaHours ?? 72} className={control}/></Field></div><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={editing?.isActive ?? true}/>Active for new requests</label><div className="flex gap-2"><button className={button}>Save category</button>{editing && <button type="button" className={secondary} onClick={() => setEditing(null)}>Cancel edit</button>}</div></fieldset></form></Card><Card title="Request categories">{!items.length ? <Empty>No categories configured. General requests use the default SLA.</Empty> : items.map(c => <article key={c.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{c.name}</h3><Badge value={c.isActive ? 'ACTIVE' : 'INACTIVE'}/></div><p className="text-sm text-slate-500">{c.code} · Response {c.responseSlaHours}h · Resolution {c.resolutionSlaHours}h</p><button disabled={action.busy} className={secondary} onClick={() => setEditing(c)}>Edit category</button></article>)}</Card></div></div>;
}
function Reporting() {
  const [report, setReport] = useState<api.HrReport | null>(null); const action = useAction(); async function load() { setReport(await api.getHrReport()); }
  useEffect(() => { void action.run(load); }, []);
  return <div className="space-y-6"><Notice error={action.error} message={action.message}/><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh report</button>{report && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Total requests', report.total], ['Response SLA breaches', report.responseBreaches], ['Resolution SLA breaches', report.resolutionBreaches], ['Average resolution hours', report.averageResolutionHours === null ? 'No resolved requests' : report.averageResolutionHours.toFixed(1)]].map(([label, value]) => <Card key={String(label)} title={String(label)}><p className="text-2xl font-semibold">{value}</p></Card>)}</div><p className="text-sm text-slate-500">All-time company totals. Breaches include completed requests that missed their deadline; average resolution time covers requests with a resolution timestamp.</p><div className="grid gap-6 lg:grid-cols-3">{[['Status', report.byStatus], ['Priority', report.byPriority], ['Category', report.byCategory]].map(([title, counts]) => <Card key={String(title)} title={`By ${String(title).toLowerCase()}`}>{Object.entries(counts as Record<string, number>).length ? Object.entries(counts as Record<string, number>).map(([key, count]) => <div className="flex justify-between gap-3 text-sm" key={key}><span>{key}</span><strong>{count}</strong></div>) : <Empty>No requests.</Empty>}</Card>)}</div></>}</div>;
}
