import { workforceRequest as request } from './api';
export const platformFeatures = ['CORE_HR','LEAVE','ATTENDANCE','TIMESHEETS','PAYROLL','PAYSLIPS','WHATSAPP','EARLY_PAY','WORKFORCE_INSIGHTS','EXECUTIVE_DASHBOARD'] as const;
export type PlatformFeature = typeof platformFeatures[number];
export type OrganizationStatus = 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'REJECTED';
export type PlatformIdentity = { id: string; fullName?: string; email: string; role: string; organizationId: string | null };
export type PlatformUser = PlatformIdentity & { isActive: boolean; createdAt?: string };
export type TenantFeature = { feature: PlatformFeature; enabled: boolean; effectiveEnabled: boolean; configured: boolean; enabledAt: string | null; disabledAt: string | null };
export type PlatformOrganization = { id: string; name: string; status: OrganizationStatus; legalName?: string | null; email?: string | null; phoneNumber?: string | null; registrationNumber?: string | null; createdAt: string; _count: { users: number; employees: number; departments: number }; users: PlatformUser[] };
export type PlatformPackage = { id: string; code: string; name: string; description: string | null; features: PlatformFeature[]; employeeLimit: number | null; isActive: boolean; _count?: { subscriptions: number } };
export type NewPlatformPackage = { code: string; name: string; description?: string; features: PlatformFeature[]; employeeLimit?: number; isActive: boolean };
export type PlatformSubscription = { id: string; organizationId: string; packageId: string; status: 'ACTIVE' | 'PAUSED' | 'CANCELLED'; startsAt: string; endsAt: string | null; package: PlatformPackage };
export type PlatformUsage = { organizations: number; users: number; employees: number; payrollRuns: number; attendanceEvents: number; leaveRequests: number; hrRequests: number };
export type PlatformAudit = { id: string; actorUserId: string | null; actorEmail?: string | null; action: string; entity: string; entityId: string; organizationId: string | null; reason: string | null; createdAt: string };
export type PlatformHealth = { status: 'OK' | 'DEGRADED'; database: 'OK' | 'UNAVAILABLE'; uptimeSeconds: number; checkedAt: string };
export type ConfigKey = 'SUPPORT_SESSION_MAX_MINUTES' | 'REGISTRATION_ENABLED' | 'MAINTENANCE_BANNER';
export type PlatformConfig = { key: ConfigKey; value: string; updatedAt: string; updatedByUserId: string };
export type TenantReadiness = { organizationId: string; status: OrganizationStatus; ready: boolean; progress: { completedSteps: number; totalSteps: number; percentage: number }; checklist: { key: string; ready: boolean; required: boolean }[]; counts: Record<string, number> };
export type SupportSession = { id: string; organizationId: string; targetUserId: string; expiresAt: string; revokedAt: string | null; reason: string };
export type SupportPreview = { session: { id: string; expiresAt: string; targetUserId: string }; organization: Pick<PlatformOrganization, 'id' | 'name' | 'status'>; target: PlatformUser; usage: PlatformUsage; features: Pick<TenantFeature, 'feature' | 'enabled'>[]; onboarding: { status: string; completedAt: string | null } | null; access: 'READ_ONLY_PREVIEW' };
export type TenantOnboarding = { organization: { id: string; name: string; status: OrganizationStatus }; onboarding: { status: string; completedAt?: string | null; [key: string]: unknown } };
const id = encodeURIComponent;
export const getAuthenticatedIdentity = () => request<PlatformIdentity>('auth/me');
export const getPlatformOrganizations = () => request<PlatformOrganization[]>('platform-admin/organizations');
export const getPlatformOrganization = (key: string) => request<PlatformOrganization>(`platform-admin/organizations/${id(key)}`);
export const createPlatformCompany = (payload: { organizationName: string; administratorName: string; administratorEmail: string; administratorPassword: string }) => request<{ organization: Pick<PlatformOrganization, 'id' | 'name' | 'status'>; administrator: { id: string; email: string } }>('platform-admin/organizations', 'POST', payload);
export const changeTenantStatus = (key: string, status: OrganizationStatus, reason: string) => request<PlatformOrganization>(`platform-admin/organizations/${id(key)}/status`, 'PATCH', { status, reason });
export const getTenantFeatures = (key: string) => request<TenantFeature[]>(`platform-admin/organizations/${id(key)}/features`);
export const setTenantFeature = (key: string, feature: PlatformFeature, enabled: boolean, reason: string) => request<unknown>(`platform-admin/organizations/${id(key)}/features/${feature}`, 'PUT', { enabled, reason });
export const getTenantReadiness = (key: string) => request<TenantReadiness>(`platform-admin/organizations/${id(key)}/readiness`);
export const getTenantOnboarding = (key: string) => request<TenantOnboarding>(`platform-admin/organizations/${id(key)}/onboarding`);
export const getPlatformPackages = () => request<PlatformPackage[]>('platform-admin/packages');
export const savePlatformPackage = (payload: NewPlatformPackage) => request<PlatformPackage>('platform-admin/packages', 'PUT', payload);
export const getTenantSubscription = (key: string) => request<PlatformSubscription | null>(`platform-admin/organizations/${id(key)}/subscription`);
export const setTenantSubscription = (key: string, payload: { packageId: string; status: PlatformSubscription['status']; endsAt?: string; reason: string }) => request<PlatformSubscription>(`platform-admin/organizations/${id(key)}/subscription`, 'PUT', payload);
export const getPlatformUsers = (organizationId?: string) => request<PlatformUser[]>(`platform-admin/users${organizationId ? `?${new URLSearchParams({ organizationId })}` : ''}`);
export const createPlatformUser = (payload: { fullName: string; email: string; password: string; role: 'PLATFORM_ADMIN' | 'COMPANY_ADMIN'; organizationId?: string }) => request<PlatformUser>('platform-admin/users', 'POST', payload);
export const setPlatformUserActive = (key: string, isActive: boolean, reason: string) => request<Pick<PlatformUser, 'id' | 'isActive'>>(`platform-admin/users/${id(key)}/status`, 'PATCH', { isActive, reason });
export const getPlatformUsage = (organizationId?: string) => request<PlatformUsage>(`platform-admin/usage${organizationId ? `?${new URLSearchParams({ organizationId })}` : ''}`);
export const getPlatformAudit = (organizationId?: string) => request<PlatformAudit[]>(organizationId ? `platform-admin/organizations/${id(organizationId)}/audit` : 'platform-admin/audit');
export const getPlatformHealth = () => request<PlatformHealth>('platform-admin/health');
export const getPlatformConfiguration = () => request<PlatformConfig[]>('platform-admin/configuration');
export const setPlatformConfiguration = (key: ConfigKey, value: string) => request<PlatformConfig>(`platform-admin/configuration/${key}`, 'PUT', { value });
export const startSupportSession = (key: string, targetUserId: string, reason: string) => request<SupportSession>(`platform-admin/organizations/${id(key)}/support-sessions`, 'POST', { targetUserId, reason });
export const previewSupportSession = (key: string) => request<SupportPreview>(`platform-admin/support-sessions/${id(key)}/preview`);
export const revokeSupportSession = (key: string) => request<SupportSession>(`platform-admin/support-sessions/${id(key)}/revoke`, 'POST');
export const tenantTransitions: Record<OrganizationStatus, OrganizationStatus[]> = { PENDING: ['ACTIVE','REJECTED'], ACTIVE: ['SUSPENDED'], SUSPENDED: ['ACTIVE'], REJECTED: [] };
export function validatePackageFeatures(features: PlatformFeature[]) {
  if (!features.includes('CORE_HR')) throw new Error('Packages must include CORE_HR.');
  if ((features.includes('PAYSLIPS') || features.includes('EARLY_PAY')) && !features.includes('PAYROLL')) throw new Error('PAYSLIPS and EARLY_PAY require PAYROLL.');
}
