'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {downloadPayslipPdf,getPayslips,sendPayslipWhatsApp,updatePayslipStatus,type Payslip,type PayslipStatus} from '../../lib/api';
const money=(v?:number|null,c='ZAR')=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:c}).format(v??0);
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium'}).format(new Date(v)):'—';
export default function PayslipsPage(){const [items,setItems]=useState<Payslip[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('ALL');
 async function load(){try{setLoading(true);setError('');const d=await getPayslips();setItems(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:'Failed to load payslips')}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 const visible=useMemo(()=>items.filter(p=>(filter==='ALL'||p.status===filter)&&(`${p.payslipNumber} ${p.employee?.firstName??''} ${p.employee?.lastName??''}`.toLowerCase().includes(query.toLowerCase()))),[items,filter,query]); const issued=items.filter(p=>p.status==='ISSUED').length,draft=items.filter(p=>p.status==='DRAFT').length,net=items.reduce((s,p)=>s+(p.payroll?.netPay??0),0);
 async function status(id:string,s:PayslipStatus){try{setBusy(id);setError('');await updatePayslipStatus(id,{status:s});setSuccess(`Payslip marked as ${s.toLowerCase()}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Failed to update payslip')}finally{setBusy('')}}
 async function pdf(id:string){try{setBusy(id);setError('');await downloadPayslipPdf(id)}catch(e){setError(e instanceof Error?e.message:'Failed to download PDF')}finally{setBusy('')}}
 async function whatsapp(id:string){try{setBusy(id);setError('');await sendPayslipWhatsApp(id);setSuccess('Payslip sent to the employee on WhatsApp.');await load()}catch(e){setError(e instanceof Error?e.message:'Failed to send WhatsApp')}finally{setBusy('')}}
 return <div className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-indigo-600">Payroll workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Payslips</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">The final payroll hand-off: issue employee payslips, download the PDF, or deliver through WhatsApp.</p></div><Link href="/payroll-runs" className="w-fit rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700">← Payroll Runs</Link></header><Workflow/>
 {(success||error)&&<div className={`rounded-2xl border px-4 py-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||success}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Payslips" value={String(items.length)} note="Generated records"/><Kpi label="Ready to issue" value={String(draft)} note="Draft payslips"/><Kpi label="Issued" value={String(issued)} note="Released to employees"/><Kpi label="Net pay represented" value={money(net)} note="Across loaded payslips"/></div>
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold text-slate-950">Employee payslips</h2><p className="mt-1 text-sm text-slate-500">Issue first, then deliver through PDF or WhatsApp.</p></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee or number…" className="rounded-xl border border-slate-200 px-3 py-2 text-sm"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="ALL">All statuses</option><option>DRAFT</option><option>ISSUED</option><option>CANCELLED</option></select></div></div>
 {loading?<Empty text="Loading payslips…"/>:!visible.length?<Empty text="No payslips match this view."/>:<div className="grid gap-4 p-5 xl:grid-cols-2">{visible.map(p=>{const c=p.payroll?.currency??'ZAR';return <article key={p.id} className="rounded-2xl border border-slate-200 p-5 transition hover:border-slate-300 hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{p.payslipNumber}</p><h3 className="mt-1 text-lg font-semibold text-slate-950">{p.employee?`${p.employee.firstName} ${p.employee.lastName}`:'Employee'}</h3><p className="mt-1 text-sm text-slate-500">{date(p.payroll?.payPeriodStart)} – {date(p.payroll?.payPeriodEnd)}</p></div><Badge status={p.status}/></div><div className="mt-5 grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3"><Metric label="Gross" value={money(p.payroll?.grossEarnings,c)}/><Metric label="Tax" value={money(p.payroll?.taxAmount,c)}/><Metric label="Net pay" value={money(p.payroll?.netPay,c)} strong/></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>Generated {date(p.generatedAt)}</span><span>{p.status==='ISSUED'?`Issued ${date(p.issuedAt)}`:'Awaiting issue'}</span></div><div className="mt-5 flex flex-wrap gap-2">{p.status==='DRAFT'&&<button onClick={()=>status(p.id,'ISSUED')} disabled={busy===p.id} className="rounded-xl bg-emerald-600 px-3.5 py-2 text-xs font-semibold text-white hover:bg-emerald-700">Issue payslip</button>}<button onClick={()=>pdf(p.id)} disabled={busy===p.id} className="rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">PDF</button><button onClick={()=>whatsapp(p.id)} disabled={busy===p.id||p.status==='CANCELLED'} className="rounded-xl border border-emerald-200 bg-emerald-50 px-3.5 py-2 text-xs font-semibold text-emerald-700 hover:bg-emerald-100">WhatsApp</button>{p.status!=='CANCELLED'&&<button onClick={()=>status(p.id,'CANCELLED')} disabled={busy===p.id} className="ml-auto px-2 py-2 text-xs text-red-600">Cancel</button>}</div></article>})}</div>}
 </section><div className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white"><p className="text-sm font-semibold">Employee delivery</p><p className="mt-1 text-sm text-slate-300">DeluxHR can finish payroll digitally: generate the payslip, issue it, then provide a PDF or deliver it through the employee WhatsApp channel.</p></div></div>}
function Workflow(){return <div className="rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50 to-white p-4"><div className="flex flex-wrap items-center gap-2">{['Timesheets','Earnings','Payroll','Payslips','Employee'].map((x,i)=><div key={x} className="flex items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${i===3?'bg-indigo-600 text-white':i<3?'bg-emerald-100 text-emerald-700':'bg-white text-slate-500 ring-1 ring-slate-200'}`}>{i<3?'✓ ':''}{x}</span>{i<4&&<span className="text-slate-300">→</span>}</div>)}</div></div>}
function Kpi({label,value,note}:{label:string,value:string,note:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>}
function Metric({label,value,strong=false}:{label:string,value:string,strong?:boolean}){return <div><p className="text-[11px] uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-1 text-sm ${strong?'font-bold text-slate-950':'font-medium text-slate-700'}`}>{value}</p></div>}
function Badge({status}:{status:string}){const c=status==='ISSUED'?'border-emerald-200 bg-emerald-50 text-emerald-700':status==='CANCELLED'?'border-red-200 bg-red-50 text-red-700':'border-amber-200 bg-amber-50 text-amber-700';return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${c}`}>{status}</span>}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-sm text-slate-500">{text}</div>}
