"use client";
import { useEffect, useState } from 'react';
import { Card, Field, Notice, control, button, secondary, useAction, text } from '@/components/leave/ui';
import { FeaturePicker, PlatformPageTitle } from '@/components/platform-admin/common';
import { getPlatformPackages, savePlatformPackage, validatePackageFeatures, type PlatformPackage, type PlatformFeature } from '@/lib/platform-api';
export default function Page(){
 const [items,setItems]=useState<PlatformPackage[]>([]),[editing,setEditing]=useState<PlatformPackage|null>(null),[features,setFeatures]=useState<PlatformFeature[]>(['CORE_HR']);const action=useAction();
 useEffect(()=>{void action.run(async()=>{setItems(await getPlatformPackages());});},[]);
 return <><PlatformPageTitle title="Edition catalogue" text="All editions are available to assign to companies. Core HR is always included."/><Notice error={action.error} message={action.message}/><details className="mb-5"><summary className="cursor-pointer font-semibold">Advanced: create a custom edition</summary><Card title={editing?'Edit package':'Create package'}><form key={editing?.id??'new'} className="grid gap-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);void action.run(async()=>{validatePackageFeatures(features);const limit=text(d,'employeeLimit');const saved=await savePlatformPackage({code:text(d,'code'),name:text(d,'name'),description:text(d,'description'),features,employeeLimit:limit?Number(limit):undefined,isActive:true});setItems(old=>[...old.filter(p=>p.id!==saved.id),{...saved,_count:old.find(p=>p.id===saved.id)?._count}]);setEditing(null);setFeatures(['CORE_HR']);form.reset();},'Package saved.');}}>
 <Field label="Code *"><input className={control} name="code" required pattern="[A-Z][A-Z0-9_]{1,31}" readOnly={!!editing} defaultValue={editing?.code}/></Field><Field label="Name *"><input className={control} name="name" required minLength={2} maxLength={100} defaultValue={editing?.name}/></Field><Field label="Description"><input className={control} name="description" maxLength={500} defaultValue={editing?.description??''}/></Field><Field label="Employee limit"><input className={control} name="employeeLimit" type="number" min={1} max={1000000} defaultValue={editing?.employeeLimit??''}/></Field><p className="text-sm text-slate-500 md:col-span-2">Leaving the limit blank keeps an existing limit; a new package has no limit.</p><div className="md:col-span-2"><FeaturePicker selected={features} onChange={setFeatures}/></div><div><button className={button} disabled={action.busy}>Save package</button>{editing&&<button type="button" className={secondary} onClick={()=>{setEditing(null);setFeatures(['CORE_HR']);}}>Cancel</button>}</div></form></Card>
 </details><Card title="Available editions"><div className="space-y-4">{items.map(p=><div key={p.id} className="rounded border p-4"><strong>{p.name} · {p.code}</strong><p>Available · {p.employeeLimit??'Unlimited'} employees · {p._count?.subscriptions??0} subscriptions</p><p className="text-sm">{p.features.join(', ')}</p><button className={secondary} disabled={action.busy||!!p._count?.subscriptions} onClick={()=>{setEditing(p);setFeatures(p.features);}}>Edit</button></div>)}</div></Card></>;
}
