'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getDepartments, getEmployees, type Department, type Employee } from '../../lib/api';
import * as api from '../../lib/people-services-api';
import { Badge, Card, Empty, Field, Notice, PageTitle, button, control, secondary, text, useAction } from '../../components/leave/ui';
type Tab = 'My inbox' | 'Announcements' | 'Communication teams';
export default function CommunicationsPage() {
  const [tab, setTab] = useState<Tab>('My inbox');
  return <div className="space-y-6"><PageTitle eyebrow="Employee services" title="Employee Communications" text="Read company announcements, acknowledge important updates, and publish targeted workforce messages."/><div className="flex flex-wrap gap-2">{(['My inbox', 'Announcements', 'Communication teams'] as Tab[]).map(t => <button key={t} className={tab === t ? button : secondary} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === 'My inbox' ? <Inbox/> : tab === 'Announcements' ? <Announcements/> : <Teams/>}</div>;
}
function Inbox() {
  const [items, setItems] = useState<api.AnnouncementReceipt[]>([]), [unread, setUnread] = useState(false), [loading, setLoading] = useState(true); const action = useAction();
  async function load(value: boolean) { try { setItems(await api.getAnnouncementInbox(value)); } finally { setLoading(false); } }
  useEffect(() => { void action.run(() => load(false)); }, []);
  return <Card title="Your announcement inbox"><Notice error={action.error} message={action.message}/><p className="text-sm text-slate-500">An active linked employee account is required. Up to 200 current announcements, with pinned items first.</p><form className="flex flex-wrap items-center gap-4" onSubmit={e => { e.preventDefault(); void action.run(() => load(unread)); }}><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={unread} onChange={e => setUnread(e.target.checked)}/>Unread only</label><button disabled={action.busy} className={secondary}>Apply / refresh</button></form>{loading ? <Empty>Loading announcements…</Empty> : !items.length ? <Empty>No announcements in this view.</Empty> : items.map(r => <article className="space-y-3 rounded-xl border border-slate-200 p-4" key={r.id}><div className="flex flex-wrap gap-2"><Badge value={r.readAt ? 'READ' : 'UNREAD'}/>{r.announcement.pinned && <Badge value="PINNED"/>}{r.announcement.important && <Badge value="IMPORTANT"/>}{r.announcement.requiresAcknowledgement && <Badge value={r.acknowledgedAt ? 'ACKNOWLEDGED' : 'ACKNOWLEDGEMENT REQUIRED'}/>}</div><Link className="block text-lg font-semibold text-indigo-700 underline" href={`/communications/${encodeURIComponent(r.announcementId)}`}>{r.announcement.title}</Link><p className="line-clamp-3 whitespace-pre-wrap text-sm text-slate-600">{r.announcement.body}</p><p className="text-xs text-slate-500">Published {api.dateTimeLabel(r.announcement.publishedAt)}{r.announcement.expiresAt ? ` · Expires ${api.dateTimeLabel(r.announcement.expiresAt)}` : ''}</p></article>)}</Card>;
}
function Announcements() {
  const [items, setItems] = useState<api.Announcement[]>([]), [departments, setDepartments] = useState<Department[]>([]), [locations, setLocations] = useState<api.WorkLocationOption[]>([]), [teams, setTeams] = useState<api.CommunicationTeam[]>([]), [optionErrors, setOptionErrors] = useState<string[]>([]);
  const [audience, setAudience] = useState<api.Audience>('COMPANY'), [target, setTarget] = useState(''); const action = useAction();
  async function load() { setItems(await api.getAnnouncements()); }
  async function loadOptions() {
    const result = await Promise.allSettled([getDepartments(), api.getCommunicationLocations(), api.getCommunicationTeams()]);
    if (result[0].status === 'fulfilled') setDepartments(result[0].value);
    if (result[1].status === 'fulfilled') setLocations(result[1].value);
    if (result[2].status === 'fulfilled') setTeams(result[2].value);
    setOptionErrors(result.flatMap((r, i) => r.status === 'rejected' ? [`${['Departments', 'Work locations', 'Communication teams'][i]}: ${r.reason instanceof Error ? r.reason.message : 'Unable to load options'}`] : []));
  }
  useEffect(() => { void action.run(load); void loadOptions(); }, []);
  const targets = audience === 'DEPARTMENT' ? departments : audience === 'LOCATION' ? locations : teams;
  return <div className="space-y-6"><Notice error={action.error} message={action.message}/>{optionErrors.length > 0 && <div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">{optionErrors.map(e => <p key={e}>{e}</p>)}</div>}<div className="grid gap-6 xl:grid-cols-2"><Card title="Create announcement"><p className="text-sm text-slate-500">Publication defaults to now. Scheduled announcements select their recipients when created; later team changes do not change that recipient list.</p><form className="space-y-4" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => {
    const title = text(d, 'title'), body = text(d, 'body'); if (title.length < 3 || body.length < 3) throw new Error('Title and message need at least three characters.');
    if (audience !== 'COMPANY' && !target) throw new Error('Select the target audience.');
    const publishedAt = text(d, 'publishedAt') ? new Date(text(d, 'publishedAt')).toISOString() : undefined;
    const expiresAt = text(d, 'expiresAt') ? new Date(text(d, 'expiresAt')).toISOString() : undefined;
    if (expiresAt && Date.parse(expiresAt) <= Date.parse(publishedAt ?? new Date().toISOString())) throw new Error('Expiry must be after publication.');
    const created = await api.createAnnouncement({ title, body, audience, ...(audience === 'DEPARTMENT' ? { departmentId: target } : audience === 'LOCATION' ? { workLocationId: target } : audience === 'TEAM' ? { teamId: target } : {}), ...(publishedAt ? { publishedAt } : {}), ...(expiresAt ? { expiresAt } : {}), pinned: d.has('pinned'), important: d.has('important'), requiresAcknowledgement: d.has('acknowledgement') });
    setItems(old => [created, ...old]); form.reset(); setAudience('COMPANY'); setTarget('');
  }, 'Announcement created. Open its details to add attachments and track recipients.'); }}><fieldset disabled={action.busy} className="space-y-4"><Field label="Title"><input name="title" required minLength={3} maxLength={120} className={control}/></Field><Field label="Message"><textarea name="body" required minLength={3} maxLength={3000} rows={6} className={control}/></Field><Field label="Audience"><select value={audience} onChange={e => { setAudience(e.target.value as api.Audience); setTarget(''); }} className={control}>{['COMPANY', 'DEPARTMENT', 'LOCATION', 'TEAM'].map(a => <option key={a}>{a}</option>)}</select></Field>{audience !== 'COMPANY' && <Field label={audience === 'DEPARTMENT' ? 'Department' : audience === 'LOCATION' ? 'Work location' : 'Communication team'}><select required value={target} onChange={e => setTarget(e.target.value)} className={control}><option value="">Select target</option>{targets.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Publish at (optional)"><input type="datetime-local" name="publishedAt" className={control}/></Field><Field label="Expire at (optional)"><input type="datetime-local" name="expiresAt" className={control}/></Field></div><p className="text-xs text-slate-500">Dates and times use your computer’s local time zone.</p><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="important"/>Important announcement</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="pinned"/>Pin in employee inbox</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="acknowledgement"/>Require employee acknowledgement</label><button className={button}>Create announcement</button></fieldset></form></Card>
  <Card title="Company announcement history"><button disabled={action.busy} className={secondary} onClick={() => void action.run(async () => { await load(); await loadOptions(); })}>Refresh history & options</button><p className="text-sm text-slate-500">Latest 200 announcements, including scheduled, inactive and expired messages.</p>{!items.length ? <Empty>No announcements loaded.</Empty> : items.map(a => <article key={a.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><Link className="font-semibold text-indigo-700 underline" href={`/communications/admin/${encodeURIComponent(a.id)}`}>{a.title}</Link><Badge value={api.announcementState(a)}/></div><div className="flex flex-wrap gap-2">{a.pinned && <Badge value="PINNED"/>}{a.important && <Badge value="IMPORTANT"/>}{a.requiresAcknowledgement && <Badge value="ACKNOWLEDGEMENT REQUIRED"/>}</div><p className="text-sm text-slate-500">{a.audience} · {a._count?.recipients ?? a.recipientCount ?? '—'} recipients</p><p className="text-xs text-slate-500">Publish {api.dateTimeLabel(a.publishedAt)}{a.expiresAt ? ` · Expire ${api.dateTimeLabel(a.expiresAt)}` : ''}</p></article>)}</Card></div></div>;
}
function Teams() {
  const [items, setItems] = useState<api.CommunicationTeam[]>([]), [employees, setEmployees] = useState<Employee[]>([]), [editing, setEditing] = useState<api.CommunicationTeam | null>(null), [selected, setSelected] = useState<string[]>([]), [query, setQuery] = useState(''); const action = useAction();
  async function load() {
    const result = await Promise.allSettled([api.getCommunicationTeams(), getEmployees()]);
    if (result[0].status === 'fulfilled') setItems(result[0].value);
    if (result[1].status === 'fulfilled') setEmployees(result[1].value);
    const failed = result.find(r => r.status === 'rejected'); if (failed?.status === 'rejected') throw failed.reason;
  }
  useEffect(() => { void action.run(load); }, []);
  function edit(team: api.CommunicationTeam | null) { setEditing(team); setSelected(team?.members.map(m => m.employeeId) ?? []); setQuery(''); }
  const options = employees.filter(e => (!e.status || e.status === 'ACTIVE') && `${e.firstName} ${e.lastName} ${e.email}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-6"><Notice error={action.error} message={action.message}/><div className="grid gap-6 xl:grid-cols-2"><Card title={editing ? 'Update communication team' : 'Create communication team'}><p className="text-sm text-slate-500">Save replaces the team’s current membership. Members must be active company employees. Existing announcements keep their recipient snapshot.</p><form key={editing?.id ?? 'new'} className="space-y-4" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => { if (selected.length > 500) throw new Error('A team supports up to 500 employees.'); const saved = await api.saveCommunicationTeam(text(d, 'name'), selected, editing?.id); setItems(old => editing ? old.map(t => t.id === saved.id ? saved : t) : [...old, saved]); edit(null); form.reset(); }, 'Communication team saved.'); }}><fieldset disabled={action.busy} className="space-y-4"><Field label="Team name"><input name="name" required minLength={2} maxLength={100} defaultValue={editing?.name ?? ''} className={control}/></Field><Field label="Find employees"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name or email" className={control}/></Field><p className="text-sm text-slate-500">{selected.length} / 500 members selected</p><div className="max-h-80 space-y-2 overflow-y-auto rounded-xl border border-slate-200 p-3">{options.map(e => <label key={e.id} className="flex items-start gap-2 text-sm"><input type="checkbox" checked={selected.includes(e.id)} onChange={event => setSelected(old => event.target.checked ? [...old, e.id] : old.filter(key => key !== e.id))}/><span>{e.firstName} {e.lastName}<span className="block text-xs text-slate-500">{e.email}</span></span></label>)}{!options.length && <Empty>No matching active employees.</Empty>}</div>{selected.filter(key => !employees.some(e => e.id === key && (!e.status || e.status === 'ACTIVE'))).map(key => <div key={key} className="flex flex-wrap items-center gap-2 text-xs text-amber-800"><span>Existing member {key} is unavailable/inactive.</span><button type="button" className={secondary} onClick={() => setSelected(old => old.filter(id => id !== key))}>Remove member</button></div>)}<div className="flex gap-2"><button className={button}>Save team</button>{editing && <button type="button" className={secondary} onClick={() => edit(null)}>Cancel edit</button>}</div></fieldset></form></Card><Card title="Communication teams"><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh teams</button>{!items.length ? <Empty>No communication teams.</Empty> : items.map(t => <div key={t.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">{t.name}</h3><p className="text-sm text-slate-500">{t.members.length} members</p><button disabled={action.busy} className={secondary} onClick={() => edit(t)}>Edit name & members</button></div>)}</Card></div></div>;
}
