'use client';
import { useEffect, useState } from 'react';
import { dateTimeLabel } from '../../lib/people-services-api';
import * as api from '../../lib/platform-api';
import { usePlatformIdentity } from './platform-shell';
import { Badge, Card, Empty, Field, Notice, PageTitle, button, control, secondary, text, useAction } from '../leave/ui';
export function UsageCards({ usage }: { usage: api.PlatformUsage }) { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(usage).map(([key, value]) => <Card key={key} title={key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())}><p className="text-3xl font-semibold">{value}</p></Card>)}</div>; }
export function FeaturePicker({ selected, onChange }: { selected: api.PlatformFeature[]; onChange: (features: api.PlatformFeature[]) => void }) { return <fieldset className="space-y-3"><legend className="text-sm font-medium">Package features</legend>{api.platformFeatures.map(feature => <label key={feature} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(feature)} disabled={feature === 'CORE_HR'} onChange={e => onChange(e.target.checked ? [...selected, feature] : selected.filter(f => f !== feature))}/>{feature.replaceAll('_', ' ')}{feature === 'CORE_HR' ? ' (required)' : ''}</label>)}</fieldset>; }
export function PlatformAuditView({ organizationId }: { organizationId?: string }) {
  const [items, setItems] = useState<api.PlatformAudit[]>([]), [loaded, setLoaded] = useState(false), [query, setQuery] = useState(''); const action = useAction();
  async function load() { setItems(await api.getPlatformAudit(organizationId)); setLoaded(true); }
  useEffect(() => { void action.run(load); }, [organizationId]);
  const filtered = items.filter(e => `${e.action} ${e.reason ?? ''} ${e.actorEmail ?? e.actorUserId} ${e.organizationId ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  return <Card title={organizationId ? 'Company audit history' : 'Platform audit history'}><Notice error={action.error} message={action.message}/><p className="text-sm text-slate-500">Latest 200 events returned by the API. Search filters these loaded events.</p><Field label="Search action, actor, reason or company"><input value={query} onChange={e => setQuery(e.target.value)} className={control}/></Field><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh audit</button>{loaded && !filtered.length ? <Empty>No events in this view.</Empty> : filtered.map(event => <article key={event.id} className="space-y-2 rounded-xl border border-slate-200 p-4"><p className="text-sm font-semibold">{event.action.replaceAll('_', ' ')}</p>{event.reason && <p className="whitespace-pre-wrap text-sm">{event.reason}</p>}<p className="break-all text-xs text-slate-500">{dateTimeLabel(event.createdAt)} · {event.actorEmail ?? event.actorUserId ?? 'Unknown actor'}</p><p className="break-all text-xs text-slate-400">{event.entity} · {event.entityId}{event.organizationId ? ` · Company ${event.organizationId}` : ''}</p></article>)}</Card>;
}
export function PlatformUsers({ organizationId }: { organizationId?: string }) {
  const [users, setUsers] = useState<api.PlatformUser[]>([]), [loaded, setLoaded] = useState(false); const identity = usePlatformIdentity(), superAdmin = identity?.role === 'SUPER_ADMIN'; const action = useAction();
  async function load() { setUsers(await api.getPlatformUsers(organizationId)); setLoaded(true); }
  useEffect(() => { void action.run(load); }, [organizationId]);
  return <div className="space-y-6"><Notice error={action.error} message={action.message}/><Card title={organizationId ? 'Company users & administrators' : 'Platform administrator accounts'}><p className="text-sm text-slate-500">Latest 200 accounts. {superAdmin ? 'Super-admin access is required for account creation and status changes.' : 'You can view accounts; creation and status changes require a super administrator.'}</p><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh users</button>{loaded && !users.length ? <Empty>No accounts found.</Empty> : users.map(user => <div key={user.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{user.fullName || user.email}</h3><Badge value={user.isActive ? 'ACTIVE' : 'INACTIVE'}/></div><p className="text-sm text-slate-500">{user.email} · {user.role}</p>{superAdmin && user.role !== 'SUPER_ADMIN' && user.id !== identity?.id && <UserStatus user={user} onSaved={load}/>}</div>)}</Card>
  {superAdmin && <Card title={organizationId ? 'Create company administrator' : 'Create platform administrator'}><form className="grid gap-4 md:grid-cols-2" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, data = new FormData(form); void action.run(async () => { const fullName = text(data, 'name'), password = String(data.get('password') ?? ''); if (fullName.length < 2) throw new Error('Enter a name of at least two characters.'); await api.createPlatformUser({ fullName, email: text(data, 'email'), password, role: organizationId ? 'COMPANY_ADMIN' : 'PLATFORM_ADMIN', ...(organizationId ? { organizationId } : {}) }); form.reset(); try { await load(); } catch { throw new Error('Account created, but refreshing failed. Refresh the user list; do not create it again.'); } }, 'Administrator created.'); }}><Field label="Full name"><input name="name" required minLength={2} maxLength={120} className={control}/></Field><Field label="Email"><input type="email" name="email" required className={control}/></Field><Field label="Initial password (12–128 characters)"><input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password" className={control}/></Field><div className="flex items-end"><button disabled={action.busy} className={button}>Create administrator</button></div></form></Card>}</div>;
}
function UserStatus({ user, onSaved }: { user: api.PlatformUser; onSaved: () => Promise<void> }) {
  const action = useAction();
  return <form className="space-y-3" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, data = new FormData(form); void action.run(async () => { const reason = text(data, 'reason'); if (reason.length < 8) throw new Error('Provide a reason of at least eight characters.'); if (!window.confirm(`${user.isActive ? 'Deactivate' : 'Reactivate'} ${user.email}?`)) return false; await api.setPlatformUserActive(user.id, !user.isActive, reason); form.reset(); try { await onSaved(); } catch { throw new Error('Account status saved, but refreshing failed. Refresh the list.'); } }, 'Account status updated.'); }}><Notice error={action.error} message={action.message}/><Field label="Reason for account status change"><textarea name="reason" required minLength={8} maxLength={500} className={control}/></Field><button disabled={action.busy} className={secondary}>{user.isActive ? 'Deactivate account' : 'Reactivate account'}</button><p className="text-xs text-slate-500">The API protects your own account, super administrators and the last active company administrator.</p></form>;
}
export function PlatformPageTitle({ title, text: description }: { title: string; text: string }) { return <PageTitle eyebrow="Platform administration" title={title} text={description}/>; }
