'use client';
import Link from 'next/link';
import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { getAuthenticatedIdentity, type PlatformIdentity } from '../../lib/platform-api';
import { homeForRole, logout } from '../../lib/auth';
import { Empty, Notice, button, secondary } from '../leave/ui';
const SessionContext = createContext<PlatformIdentity | null>(null);
export const usePlatformIdentity = () => useContext(SessionContext);
export const platformNavigation = [ { label: 'Overview', href: '/platform-admin' }, { label: 'Companies', href: '/platform-admin/companies' }, { label: 'Employer repayments', href: '/platform-admin/early-pay-repayments' }, { label: 'Early Pay treasury', href: '/platform-admin/early-pay-treasury' }, { label: 'Packages', href: '/platform-admin/packages' }, { label: 'Platform users', href: '/platform-admin/users' }, { label: 'Audit logs', href: '/platform-admin/audit' }, { label: 'Configuration', href: '/platform-admin/configuration' } ];
export function PlatformShell({ children }: { children: ReactNode }) {
  const [identity, setIdentity] = useState<PlatformIdentity | null>(null), [checked, setChecked] = useState(false), [error, setError] = useState(''), [menu, setMenu] = useState(false); const pathname = usePathname(), router = useRouter();
  async function verify() { setChecked(false); setError(''); try { const user = await getAuthenticatedIdentity(); if (!['SUPER_ADMIN','PLATFORM_ADMIN'].includes(user.role) || user.organizationId !== null) throw new Error('A platform administrator account without a company association is required.'); setIdentity(user); localStorage.setItem('user', JSON.stringify(user)); } catch (e) { setIdentity(null); setError(e instanceof Error ? e.message : 'Unable to verify platform access.'); } finally { setChecked(true); } }
  useEffect(() => { void verify(); }, []);
  function signOut() { logout(); router.push('/login'); router.refresh(); }
  if (!checked) return <div className="min-h-screen bg-slate-50 p-8"><Empty>Verifying platform access…</Empty></div>;
  if (!identity) return <main className="mx-auto max-w-xl space-y-5 p-8"><h1 className="text-2xl font-semibold">Platform administration</h1><Notice error={error} message=""/><div className="flex flex-wrap gap-2"><button className={secondary} onClick={() => void verify()}>Retry access check</button><Link href="/dashboard" className={secondary}>Company workspace</Link><button className={button} onClick={signOut}>Sign out</button></div></main>;
  const active = (href: string) => href === '/platform-admin' ? pathname === href : pathname === href || pathname.startsWith(href + '/') || href.endsWith('/companies') && pathname.startsWith('/platform-admin/organizations/');
  return <SessionContext.Provider value={identity}><div className="min-h-screen bg-slate-50"><aside className="fixed inset-y-0 left-0 hidden w-64 flex-col border-r border-slate-200 bg-white p-5 md:flex"><Link className="text-xl font-bold text-slate-950" href={homeForRole(identity.role)}>DeluxHR</Link><p className="mt-1 text-xs text-indigo-600">Platform Administration</p><nav className="mt-8 space-y-2">{platformNavigation.map(item => <Link key={item.href} href={item.href} className={`block rounded-xl px-3 py-3 text-sm font-medium ${active(item.href) ? 'bg-indigo-50 text-indigo-700' : 'text-slate-600 hover:bg-slate-50'}`}>{item.label}</Link>)}</nav><button onClick={signOut} className={`${secondary} mt-auto`}>Sign out</button></aside><div className="md:pl-64"><header className="sticky top-0 z-30 flex min-h-16 flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-white p-4"><div className="flex items-center gap-3"><button className={secondary + ' md:hidden'} aria-label="Open platform navigation" onClick={() => setMenu(true)}>Menu</button><p className="font-semibold text-slate-900">Platform workspace</p></div><div className="text-right text-xs text-slate-500"><p className="font-semibold text-slate-800">{identity.role}</p><p>{identity.email}</p></div></header><main className="mx-auto max-w-[1600px] space-y-6 p-4 md:p-7">{children}</main></div>{menu && <div className="fixed inset-0 z-50 md:hidden"><button className="absolute inset-0 bg-slate-950/40" aria-label="Close platform navigation" onClick={() => setMenu(false)}/><aside className="absolute inset-y-0 left-0 w-72 overflow-y-auto bg-white p-5"><div className="mb-6 flex items-center justify-between"><p className="font-bold">DeluxHR Platform</p><button className={secondary} onClick={() => setMenu(false)}>Close</button></div>{platformNavigation.map(item => <Link key={item.href} onClick={() => setMenu(false)} href={item.href} className={`mb-2 block rounded-xl p-3 text-sm ${active(item.href) ? 'bg-indigo-50 text-indigo-700' : 'text-slate-700'}`}>{item.label}</Link>)}<button className={secondary + ' mt-5'} onClick={signOut}>Sign out</button></aside></div>}</div></SessionContext.Provider>;
}
