ALTER TABLE "EmployeePayrollProfile" ADD COLUMN "dateOfBirth" TIMESTAMP(3);
ALTER TABLE "PayrollRun" ADD COLUMN "uifEmployee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "uifEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "sdlEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "employeeBenefitDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "employerContributions" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "recurringDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "earlyPayRecovery" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "totalEmployerCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "taxYear" TEXT,
ADD COLUMN "calculationBreakdown" JSONB;
