'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { generatePayrollRun, getEarnings, updateEarningStatus, type Earning, type PayrollItemStatus } from '../../lib/api';

const money=(v:number,c='ZAR')=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:c}).format(v);
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium'}).format(new Date(v)):'—';
const period=(e:Earning)=>`${date(e.payPeriodStart)} – ${date(e.payPeriodEnd)}`;

export default function EarningsPage(){
 const [items,setItems]=useState<Earning[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('ALL');
 async function load(){try{setLoading(true);setError('');const d=await getEarnings();setItems(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:'Failed to load earnings')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>items.filter(e=>(filter==='ALL'||e.status===filter)&&(`${e.employee?.firstName??''} ${e.employee?.lastName??''} ${e.title} ${e.type}`.toLowerCase().includes(query.toLowerCase()))),[items,query,filter]);
 const approved=items.filter(x=>x.status==='APPROVED'), pending=items.filter(x=>x.status==='PENDING');
 const approvedValue=approved.reduce((s,x)=>s+x.amount,0), total=items.reduce((s,x)=>s+x.amount,0);
 async function status(id:string,s:PayrollItemStatus){try{setBusy(id);setError('');setSuccess('');await updateEarningStatus(id,{status:s});setSuccess(`Earning marked as ${s.toLowerCase()}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Failed to update earning')}finally{setBusy('')}}
 async function payroll(){const e=approved[0];if(!e){setError('No approved earnings are ready for payroll.');return}try{setBusy('payroll');setError('');await generatePayrollRun({employeeId:e.employeeId,payPeriodStart:e.payPeriodStart,payPeriodEnd:e.payPeriodEnd,paymentDate:new Date().toISOString(),title:'Generated payroll run'});setSuccess('Payroll run generated. Continue to Payroll Runs to review it.');await load()}catch(x){setError(x instanceof Error?x.message:'Failed to generate payroll')}finally{setBusy('')}}
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-indigo-600">Payroll workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Earnings</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Validate employee earnings before they become payroll. Approved items are the hand-off point into a payroll run.</p></div><div className="flex gap-2"><Link href="/timesheets" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700 hover:bg-slate-50">← Timesheets</Link><button onClick={payroll} disabled={busy==='payroll'||!approved.length} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700 disabled:opacity-50">{busy==='payroll'?'Generating…':`Generate payroll (${approved.length})`}</button></div></header>
  <Workflow active={1}/>
  {(success||error)&&<div className={`rounded-2xl border px-4 py-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||success}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Earning records" value={String(items.length)} note="Current payroll items"/><Kpi label="Pending review" value={String(pending.length)} note="Need an approval decision"/><Kpi label="Approved value" value={money(approvedValue)} note={`${approved.length} ready for payroll`}/><Kpi label="Total earnings" value={money(total)} note="Across loaded records"/></div>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold text-slate-950">Earning register</h2><p className="mt-1 text-sm text-slate-500">Review source, pay period and value before processing.</p></div><div className="flex flex-col gap-2 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee or earning…" className="rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-indigo-400"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="ALL">All statuses</option><option>PENDING</option><option>APPROVED</option><option>PROCESSED</option><option>CANCELLED</option></select></div></div>
   {loading?<Empty text="Loading earnings…"/>:!visible.length?<Empty text="No earnings match this view."/>:<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Earning</th><th className="px-5 py-3">Pay period</th><th className="px-5 py-3">Calculation</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map(e=><tr key={e.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><p className="font-medium text-slate-900">{e.employee?`${e.employee.firstName} ${e.employee.lastName}`:e.employeeId}</p><p className="mt-1 text-xs text-slate-500">{e.employee?.department?.name??'Employee'}</p></td><td className="px-5 py-4"><p className="font-medium text-slate-800">{e.title}</p><p className="mt-1 text-xs text-slate-500">{e.type}{e.source?` • ${e.source}`:''}</p></td><td className="px-5 py-4 text-slate-600">{period(e)}<p className="mt-1 text-xs text-slate-400">Earned {date(e.earnedDate)}</p></td><td className="px-5 py-4 text-slate-600">{e.units??'—'} {e.units!=null?'units':''}{e.rate!=null?<p className="text-xs text-slate-400">@ {money(e.rate,e.currency)}</p>:null}</td><td className="px-5 py-4 font-semibold text-slate-950">{money(e.amount,e.currency)}</td><td className="px-5 py-4"><Badge status={e.status}/></td><td className="px-5 py-4"><div className="flex gap-2">{e.status==='PENDING'&&<button onClick={()=>status(e.id,'APPROVED')} disabled={busy===e.id} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700 hover:bg-emerald-100">Approve</button>}{e.status!=='CANCELLED'&&e.status!=='PROCESSED'&&<button onClick={()=>status(e.id,'CANCELLED')} disabled={busy===e.id} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-50">Cancel</button>}{e.status==='PROCESSED'&&<span className="text-xs text-slate-500">Included in payroll</span>}</div></td></tr>)}</tbody></table></div>}
  </section>
 </div>
}
function Workflow({active}:{active:number}){const s=['Timesheets','Earnings','Payroll','Payslips','Employee'];return <div className="rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50 to-white p-4"><div className="flex flex-wrap items-center gap-2">{s.map((x,i)=><div key={x} className="flex items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${i===active?'bg-indigo-600 text-white':i<active?'bg-emerald-100 text-emerald-700':'bg-white text-slate-500 ring-1 ring-slate-200'}`}>{i<active?'✓ ':''}{x}</span>{i<s.length-1&&<span className="text-slate-300">→</span>}</div>)}</div></div>}
function Kpi({label,value,note}:{label:string,value:string,note:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>}
function Badge({status}:{status:string}){const c=status==='APPROVED'||status==='PROCESSED'?'border-emerald-200 bg-emerald-50 text-emerald-700':status==='CANCELLED'?'border-red-200 bg-red-50 text-red-700':'border-amber-200 bg-amber-50 text-amber-700';return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${c}`}>{status}</span>}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-sm text-slate-500">{text}</div>}
