'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { type LeaveRequest } from '../../../lib/api';
import { getUser } from '../../../lib/auth';
import * as api from '../../../lib/leave-api';
import { Badge, Card, Empty, Field, Notice, PageTitle, button, control, dateLabel, secondary, text, useAction } from '../../../components/leave/ui';

export default function LeaveRequestDetailPage() {
  const params = useParams<{ id: string }>(); const id = params.id;
  const [request, setRequest] = useState<LeaveRequest | null>(null), [history, setHistory] = useState<api.LeaveHistory | null>(null), [loading, setLoading] = useState(true), [requestError, setRequestError] = useState('');
  const [canManage, setCanManage] = useState(false), [isOwner, setIsOwner] = useState(false), [kind, setKind] = useState<'CANCELLATION' | 'AMENDMENT'>('CANCELLATION');
  const action = useAction();
  async function load() {
    const results = await Promise.allSettled([api.getLeaveRequest(id), api.getLeaveHistory(id)]);
    if (results[0].status === 'fulfilled') {
      setRequest(results[0].value); setRequestError('');
      setIsOwner(results[0].value.employee?.userId === getUser()?.id);
    } else { setRequest(null); setIsOwner(false); setRequestError(results[0].reason instanceof Error ? results[0].reason.message : 'Request summary unavailable.'); }
    if (results[1].status === 'fulfilled') setHistory(results[1].value);
    else { setHistory(null); setLoading(false); throw results[1].reason; }
    setLoading(false);
  }
  useEffect(() => { setRequest(null); setHistory(null); setLoading(true); setCanManage(['HR_ADMIN', 'COMPANY_ADMIN'].includes(getUser()?.role ?? '')); void action.run(load); }, [id]);
  const pendingChange = history?.changes.some(c => c.status === 'PENDING');
  const canEdit = canManage || isOwner;
  const title = request?.employee ? `${request.employee.firstName} ${request.employee.lastName}` : 'Leave request details';
  return <div className="space-y-6"><PageTitle title={title} text="Supporting documents, approval steps, comments, cancellations and amendments."/><div className="flex flex-wrap gap-2"><Link className={secondary} href="/leave-requests">All requests</Link><Link className={secondary} href="/leave-approvals">My approval queue</Link><button className={secondary} disabled={action.busy} onClick={() => void action.run(load)}>Refresh details</button></div><Notice error={action.error} message={action.message}/>
    {requestError && <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Request summary: {requestError} Available documents and workflow history are shown below.</p>}
    {request && <Card title="Request summary"><Badge value={request.status}/><p className="text-sm">{request.leaveType?.name ?? 'Leave'} · {dateLabel(request.startDate)} → {dateLabel(request.endDate)}</p><p className="text-sm text-slate-500">{request.chargedDays != null ? `${request.chargedDays} charged working days` : request.requestedWorkingDays != null ? `${request.requestedWorkingDays} requested working days` : 'Working days are calculated by the policy engine on approval.'}</p><p className="break-all text-xs text-slate-400">Reference: {id}</p>{request.approvalWorkflowId && <p className="text-sm text-indigo-700">Approval follows the configured chain. Use your approval queue to record a decision.</p>}</Card>}
    {loading ? <Empty>Loading request history…</Empty> : history && <>
    <div className="grid gap-6 xl:grid-cols-2"><Card title="Approval history">{!history.decisions.length ? <Empty>No approval chain attached to this request.</Empty> : history.decisions.map(d => <div key={d.id} className="space-y-2 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">Step {d.step.order} · {d.step.kind}</p><Badge value={d.status}/></div><p className="break-all text-xs text-slate-500">Assigned user: {d.step.approverUserId}</p>{d.comment && <p className="whitespace-pre-wrap text-sm">{d.comment}</p>}{d.decidedAt && <p className="text-xs text-slate-500">{dateLabel(d.decidedAt)} · Decision by {d.decidedByUserId}</p>}</div>)}</Card>
    <Card title="Supporting documents">{!history.documents.length ? <Empty>No documents uploaded.</Empty> : history.documents.map(d => <div key={d.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div className="min-w-0"><p className="break-all text-sm font-medium">{d.originalFileName}</p><p className="mt-1 text-xs text-slate-500">{d.kind.replaceAll('_', ' ')} · {(d.fileSizeBytes / 1024).toFixed(1)} KB · {dateLabel(d.createdAt)}</p></div><button disabled={action.busy} className={secondary} onClick={() => void action.run(async () => { await api.downloadLeaveDocument(id, d); })}>Download</button></div>)}
    {canEdit && <form className="space-y-4 border-t border-slate-100 pt-4" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, data = new FormData(form), file = data.get('file'); void action.run(async () => { if (!(file instanceof File) || !file.size) throw new Error('Choose a document.'); await api.uploadLeaveDocument(id, text(data, 'kind') as api.LeaveDocument['kind'], file); await load(); form.reset(); }, 'Document uploaded.'); }}><Field label="Document kind"><select name="kind" className={control}><option value="SUPPORTING">Supporting document</option><option value="MEDICAL_CERTIFICATE">Medical certificate</option></select></Field><Field label="PDF, PNG or JPEG (maximum 10 MB)"><input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required className={control}/></Field><button disabled={action.busy} className={button}>Upload document</button></form>}
    </Card></div>
    <Card title="Comments & HR notes">{!history.comments.length ? <Empty>No comments recorded.</Empty> : history.comments.map(c => <div key={c.id} className="space-y-2 rounded-xl border border-slate-200 p-4"><Badge value={c.internal ? 'INTERNAL HR NOTE' : 'COMMENT'}/><p className="whitespace-pre-wrap text-sm">{c.text}</p><p className="break-all text-xs text-slate-500">{dateLabel(c.createdAt)} · {c.actorUserId}</p></div>)}{canEdit && <form className="space-y-3" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => { await api.addLeaveComment(id, text(d, 'comment'), d.has('internal')); await load(); form.reset(); }, 'Comment recorded.'); }}><Field label="Comment"><textarea name="comment" required maxLength={2000} className={control}/></Field>{canManage && <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="internal"/>Internal HR note</label>}<button disabled={action.busy} className={button}>Add comment</button></form>}</Card>
    <Card title="Cancellations & amendments">{!history.changes.length ? <Empty>No changes requested.</Empty> : history.changes.map(c => <div key={c.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium">{c.kind}</h3><Badge value={c.status}/></div><p className="whitespace-pre-wrap text-sm">{c.reason}</p>{c.proposedStart && c.proposedEnd && <p className="text-sm text-slate-500">Proposed dates: {dateLabel(c.proposedStart)} → {dateLabel(c.proposedEnd)}</p>}{c.reviewNote && <p className="whitespace-pre-wrap text-sm text-slate-500">Review: {c.reviewNote}</p>}<p className="text-xs text-slate-400">Requested {dateLabel(c.createdAt)}{c.reviewedAt ? ` · Reviewed ${dateLabel(c.reviewedAt)}` : ''}</p>{canManage && c.status === 'PENDING' && <form className="space-y-3" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => { await api.reviewLeaveChange(c.id, text(d, 'status') as 'APPROVED' | 'REJECTED', text(d, 'note')); await load(); form.reset(); }, 'Change reviewed.'); }}><Field label="Review decision"><select name="status" className={control}><option value="APPROVED">Approve change</option><option value="REJECTED">Reject change</option></select></Field><Field label="Review note"><textarea name="note" required maxLength={1000} className={control}/></Field><button disabled={action.busy} className={button}>Record review</button></form>}</div>)}
    {request?.status === 'APPROVED' && canEdit && !pendingChange && <form className="space-y-4 border-t border-slate-100 pt-4" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = new FormData(form); void action.run(async () => { const proposedStart = text(d, 'from'), proposedEnd = text(d, 'to'); if (kind === 'AMENDMENT' && proposedEnd < proposedStart) throw new Error('End date cannot precede start date.'); await api.requestLeaveChange(id, { kind, reason: text(d, 'reason'), ...(kind === 'AMENDMENT' ? { proposedStart, proposedEnd } : {}) }); await load(); form.reset(); }, 'Change requested for HR review.'); }}><Field label="Change type"><select disabled={action.busy} value={kind} onChange={e => setKind(e.target.value as typeof kind)} className={control}><option value="CANCELLATION">Cancel approved leave</option><option value="AMENDMENT">Amend leave dates</option></select></Field>{kind === 'AMENDMENT' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Proposed start"><input name="from" type="date" required className={control}/></Field><Field label="Proposed end"><input name="to" type="date" required className={control}/></Field></div>}<Field label="Reason"><textarea name="reason" required maxLength={1000} className={control}/></Field><button disabled={action.busy} className={button}>Request change</button></form>}
    {pendingChange && <p className="text-sm text-amber-700">A change is awaiting HR review.</p>}
    </Card></>}
  </div>;
}
