'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createLeaveRequest, getEmployees, getLeaveRequests, getLeaveTypes, updateLeaveRequestStatus, type Employee, type LeaveRequest, type LeaveType } from '../../lib/api';

type Filter = 'ALL' | LeaveRequest['status'];

export default function LeaveRequestsPage() {
  const [leaveRequests,setLeaveRequests]=useState<LeaveRequest[]>([]); const [employees,setEmployees]=useState<Employee[]>([]); const [leaveTypes,setLeaveTypes]=useState<LeaveType[]>([]);
  const [employeeId,setEmployeeId]=useState(''); const [leaveTypeId,setLeaveTypeId]=useState(''); const [startDate,setStartDate]=useState(''); const [endDate,setEndDate]=useState('');
  const [filter,setFilter]=useState<Filter>('ALL'); const [query,setQuery]=useState(''); const [isLoading,setIsLoading]=useState(true); const [isSubmitting,setIsSubmitting]=useState(false); const [actionLoadingId,setActionLoadingId]=useState<string|null>(null); const [errorMessage,setErrorMessage]=useState(''); const [successMessage,setSuccessMessage]=useState('');

  async function loadPageData(){try{setIsLoading(true);setErrorMessage('');const [r,e,t]=await Promise.all([getLeaveRequests(),getEmployees(),getLeaveTypes()]);setLeaveRequests(r);setEmployees(e);setLeaveTypes(t);}catch(error){setErrorMessage(error instanceof Error?error.message:'Failed to load leave requests data.');}finally{setIsLoading(false);}}
  useEffect(()=>{loadPageData();},[]);

  const counts={pending:leaveRequests.filter((r)=>r.status==='PENDING').length,approved:leaveRequests.filter((r)=>r.status==='APPROVED').length,rejected:leaveRequests.filter((r)=>r.status==='REJECTED').length};
  const filtered=useMemo(()=>leaveRequests.filter((r)=>{const name=r.employee?`${r.employee.firstName} ${r.employee.lastName}`:'';const hay=`${name} ${r.employee?.email??''} ${r.leaveType?.name??''}`.toLowerCase();return (filter==='ALL'||r.status===filter)&&hay.includes(query.toLowerCase());}),[leaveRequests,filter,query]);

  async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();setErrorMessage('');setSuccessMessage('');if(!employeeId||!leaveTypeId||!startDate||!endDate){setErrorMessage('Employee, leave type, start date, and end date are required.');return;}if(new Date(endDate)<new Date(startDate)){setErrorMessage('End date cannot be before the start date.');return;}try{setIsSubmitting(true);const created=await createLeaveRequest({employeeId,leaveTypeId,startDate,endDate});const employee=employees.find((e)=>e.id===employeeId);const leaveType=leaveTypes.find((t)=>t.id===leaveTypeId);setLeaveRequests((current)=>[{...created,employee:employee??created.employee,leaveType:leaveType??created.leaveType},...current]);setEmployeeId('');setLeaveTypeId('');setStartDate('');setEndDate('');setSuccessMessage('Leave request submitted for approval.');}catch(error){setErrorMessage(error instanceof Error?error.message:'Failed to create leave request.');}finally{setIsSubmitting(false);}}

  async function handleStatusUpdate(id:string,status:'APPROVED'|'REJECTED'){try{setErrorMessage('');setSuccessMessage('');setActionLoadingId(id);const updated=await updateLeaveRequestStatus(id,status);setLeaveRequests((current)=>current.map((r)=>r.id===id?{...r,...updated}:r));setSuccessMessage(status==='APPROVED'?'Leave request approved.':'Leave request rejected.');}catch(error){setErrorMessage(error instanceof Error?error.message:'Failed to update leave request.');}finally{setActionLoadingId(null);}}

  return <div className="space-y-7">
    <section className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-600">Time & leave</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Leave management</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Submit employee leave, review requests and keep approvals moving without losing visibility.</p></div><button onClick={loadPageData} className="h-10 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50">Refresh requests</button></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="All requests" value={leaveRequests.length} tone="slate"/><Metric label="Awaiting approval" value={counts.pending} tone="amber"/><Metric label="Approved" value={counts.approved} tone="green"/><Metric label="Rejected" value={counts.rejected} tone="red"/></section>

    {(errorMessage||successMessage)&&<div className={`rounded-xl border px-4 py-3 text-sm ${errorMessage?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{errorMessage||successMessage}</div>}

    <section className="grid gap-6 2xl:grid-cols-[360px_minmax(0,1fr)]">
      <div className="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 text-xl">☼</div><h2 className="mt-4 text-lg font-semibold text-slate-950">New leave request</h2><p className="mt-1 text-sm leading-6 text-slate-500">Capture a request on behalf of an employee and send it into the approval queue.</p><form onSubmit={handleSubmit} className="mt-6 space-y-4"><Field label="Employee"><select value={employeeId} onChange={(e)=>setEmployeeId(e.target.value)} className="input"><option value="">Select employee</option>{employees.map((e)=><option key={e.id} value={e.id}>{e.firstName} {e.lastName}</option>)}</select></Field><Field label="Leave type"><select value={leaveTypeId} onChange={(e)=>setLeaveTypeId(e.target.value)} className="input"><option value="">Select leave type</option>{leaveTypes.map((t)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Start date"><input type="date" value={startDate} onChange={(e)=>setStartDate(e.target.value)} className="input"/></Field><Field label="End date"><input type="date" min={startDate||undefined} value={endDate} onChange={(e)=>setEndDate(e.target.value)} className="input"/></Field></div><button disabled={isSubmitting} className="w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-500 disabled:opacity-60">{isSubmitting?'Submitting…':'Submit leave request'}</button></form></div>

      <div className="min-w-0 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-lg font-semibold text-slate-950">Approval queue</h2><p className="mt-1 text-sm text-slate-500">Review requests and act on pending leave.</p></div><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search employee or leave type…" className="h-10 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100 xl:w-72"/></div><div className="mt-5 flex flex-wrap gap-2">{(['ALL','PENDING','APPROVED','REJECTED'] as Filter[]).map((item)=><button key={item} onClick={()=>setFilter(item)} className={`rounded-lg px-3 py-2 text-xs font-semibold transition ${filter===item?'bg-slate-900 text-white':'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{item==='ALL'?'All requests':item.charAt(0)+item.slice(1).toLowerCase()}</button>)}</div></div>
        {isLoading?<div className="p-12 text-center text-sm text-slate-500">Loading leave requests…</div>:filtered.length===0?<div className="m-6 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-10 text-center"><p className="font-semibold text-slate-800">No leave requests in this view</p><p className="mt-1 text-sm text-slate-500">Change the filter or submit a new request.</p></div>:<div className="divide-y divide-slate-100">{filtered.map((r)=><RequestRow key={r.id} request={r} loading={actionLoadingId===r.id} onUpdate={handleStatusUpdate}/>)}</div>}
      </div>
    </section>
    <style jsx>{`.input{width:100%;border:1px solid rgb(226 232 240);border-radius:.75rem;background:white;padding:.72rem .9rem;font-size:.875rem;color:rgb(15 23 42);outline:none}.input:focus{border-color:rgb(129 140 248);box-shadow:0 0 0 3px rgb(224 231 255)}`}</style>
  </div>;
}

function RequestRow({request,loading,onUpdate}:{request:LeaveRequest;loading:boolean;onUpdate:(id:string,status:'APPROVED'|'REJECTED')=>void}){const name=request.employee?`${request.employee.firstName} ${request.employee.lastName}`:'Unknown employee';const days=Math.max(1,Math.floor((new Date(request.endDate).getTime()-new Date(request.startDate).getTime())/86400000)+1);return <article className="p-5 transition hover:bg-slate-50/60 sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-sm font-bold text-indigo-700">{name.split(' ').map((n)=>n[0]).slice(0,2).join('')}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-950">{name}</p><Status status={request.status}/></div><p className="mt-1 text-sm text-slate-500">{request.leaveType?.name||'Leave'} · {days} day{days===1?'':'s'}</p><p className="mt-2 text-xs text-slate-400">{fmt(request.startDate)} → {fmt(request.endDate)}{request.employee?.email?` · ${request.employee.email}`:''}</p></div></div><div className="flex shrink-0 gap-2">{request.status==='PENDING'?<><button disabled={loading} onClick={()=>onUpdate(request.id,'REJECTED')} className="rounded-xl border border-red-200 bg-white px-4 py-2 text-xs font-semibold text-red-700 hover:bg-red-50 disabled:opacity-50">Reject</button><button disabled={loading} onClick={()=>onUpdate(request.id,'APPROVED')} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-semibold text-white hover:bg-emerald-500 disabled:opacity-50">{loading?'Saving…':'Approve'}</button></>:<span className="text-xs font-medium text-slate-400">Decision recorded</span>}</div></div></article>}
function Status({status}:{status:LeaveRequest['status']}){const cls=status==='APPROVED'?'bg-emerald-50 text-emerald-700':status==='REJECTED'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700';return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${cls}`}>{status.charAt(0)+status.slice(1).toLowerCase()}</span>}
function Metric({label,value,tone}:{label:string;value:number;tone:'slate'|'amber'|'green'|'red'}){const dot={slate:'bg-slate-400',amber:'bg-amber-500',green:'bg-emerald-500',red:'bg-red-500'}[tone];return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${dot}`}/><p className="text-sm font-medium text-slate-500">{label}</p></div><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label>}
function fmt(value:string){return new Date(value).toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'});}
