'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { createLeaveRequest, getEmployees, getLeaveRequests, getLeaveTypes, updateLeaveRequestStatus, type Employee, type LeaveRequest, type LeaveType } from '../../lib/api';
import { calculateLeaveDays } from '../../lib/leave-api';
import { getUser } from '../../lib/auth';
import { Badge, Card, Empty, Field, Notice, PageTitle, button, control, dateLabel, secondary, text, useAction } from '../../components/leave/ui';

export default function LeaveRequestsPage() {
  const [requests, setRequests] = useState<LeaveRequest[]>([]), [employees, setEmployees] = useState<Employee[]>([]), [types, setTypes] = useState<LeaveType[]>([]), [loading, setLoading] = useState(true);
  const [employeeId, setEmployeeId] = useState(''), [leaveTypeId, setLeaveTypeId] = useState(''), [startDate, setStartDate] = useState(''), [endDate, setEndDate] = useState('');
  const [days, setDays] = useState<number | null>(null), [filter, setFilter] = useState('ALL'), [search, setSearch] = useState(''), [canManage, setCanManage] = useState(false);
  const action = useAction();
  async function load() {
    const results = await Promise.allSettled([getLeaveRequests(), getEmployees(), getLeaveTypes()]);
    if (results[0].status === 'fulfilled') setRequests(results[0].value);
    if (results[1].status === 'fulfilled') setEmployees(results[1].value);
    if (results[2].status === 'fulfilled') setTypes(results[2].value);
    setLoading(false);
    const failed = results.find(r => r.status === 'rejected'); if (failed?.status === 'rejected') throw failed.reason;
  }
  useEffect(() => { setCanManage(['HR_ADMIN', 'COMPANY_ADMIN'].includes(getUser()?.role ?? '')); void action.run(load); }, []);
  function validDates() { if (!employeeId || !leaveTypeId || !startDate || !endDate) throw new Error('Employee, leave type and dates are required.'); if (endDate < startDate) throw new Error('End date cannot precede start date.'); }
  const name = (r: LeaveRequest) => r.employee ? `${r.employee.firstName} ${r.employee.lastName}` : employees.find(e => e.id === r.employeeId) ? `${employees.find(e => e.id === r.employeeId)?.firstName} ${employees.find(e => e.id === r.employeeId)?.lastName}` : r.employeeId;
  const typeName = (r: LeaveRequest) => r.leaveType?.name ?? types.find(t => t.id === r.leaveTypeId)?.name ?? 'Leave';
  const filtered = requests.filter(r => (filter === 'ALL' || r.status === filter) && `${name(r)} ${typeName(r)}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><PageTitle title="Leave management" text="Capture leave requests, review policy-based working days, and open documents and approval history."/><div className="flex flex-wrap gap-2"><Link className={secondary} href="/leave-approvals">My approval queue</Link><Link className={secondary} href="/leave-policies">Policies & balances</Link><button disabled={action.busy} className={secondary} onClick={() => void action.run(load)}>Refresh requests</button></div><Notice error={action.error} message={action.message}/>
  <div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]"><Card title="New leave request"><form className="space-y-4" onSubmit={e => { e.preventDefault(); void action.run(async () => { validDates(); const created = await createLeaveRequest({ employeeId, leaveTypeId, startDate, endDate }); setRequests(old => [{ ...created, employee: employees.find(e => e.id === employeeId), leaveType: types.find(t => t.id === leaveTypeId) }, ...old]); setEmployeeId(''); setLeaveTypeId(''); setStartDate(''); setEndDate(''); setDays(null); }, 'Leave submitted. Open request details to upload supporting documents.'); }}><fieldset disabled={action.busy} className="space-y-4"><Field label="Employee"><select required value={employeeId} onChange={e => { setEmployeeId(e.target.value); setDays(null); }} className={control}><option value="">Select employee</option>{employees.map(e => <option key={e.id} value={e.id}>{e.firstName} {e.lastName}</option>)}</select></Field><Field label="Leave type"><select required value={leaveTypeId} onChange={e => { setLeaveTypeId(e.target.value); setDays(null); }} className={control}><option value="">Select leave type</option>{types.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Start date"><input type="date" required value={startDate} onChange={e => { setStartDate(e.target.value); setDays(null); }} className={control}/></Field><Field label="End date"><input type="date" required min={startDate || undefined} value={endDate} onChange={e => { setEndDate(e.target.value); setDays(null); }} className={control}/></Field>{canManage && <button type="button" className={secondary} onClick={() => void action.run(async () => { validDates(); setDays((await calculateLeaveDays({ employeeId, leaveTypeId, startDate, endDate })).days); })}>Calculate working days</button>}{days !== null && <p className="rounded-xl bg-indigo-50 p-3 text-sm text-indigo-700">{days} working days under the effective policy.</p>}<button className={button}>Submit leave request</button></fieldset></form></Card>
  <Card title="Leave requests"><Field label="Search employee or leave type"><input value={search} onChange={e => setSearch(e.target.value)} className={control}/></Field><div className="flex flex-wrap gap-2">{['ALL', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'].map(status => <button className={filter === status ? button : secondary} key={status} onClick={() => setFilter(status)}>{status}</button>)}</div>
  {loading ? <Empty>Loading requests…</Empty> : !filtered.length ? <Empty>No leave requests in this view.</Empty> : filtered.map(r => <article key={r.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{name(r)}</h3><Badge value={r.status}/></div><p className="text-sm text-slate-500">{typeName(r)} · {dateLabel(r.startDate)} → {dateLabel(r.endDate)}{r.chargedDays != null ? ` · ${r.chargedDays} charged working days` : r.requestedWorkingDays != null ? ` · ${r.requestedWorkingDays} requested working days` : ''}</p><Link className="inline-block text-sm font-medium text-indigo-700 underline" href={`/leave-requests/${encodeURIComponent(r.id)}`}>Documents, history & changes</Link>{r.status === 'PENDING' && r.approvalWorkflowId && <p className="text-sm text-slate-500">Approval follows the configured chain. Assigned reviewers use their approval queue.</p>}
  {canManage && r.status === 'PENDING' && !r.approvalWorkflowId && <form className="space-y-3 border-t border-slate-100 pt-3" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); void action.run(async () => { const updated = await updateLeaveRequestStatus(r.id, text(data, 'status') as 'APPROVED' | 'REJECTED'); setRequests(old => old.map(current => current.id === r.id ? { ...current, ...updated } : current)); }, 'Leave decision recorded.'); }}><p className="text-xs text-slate-500">This request has no approval chain. HR can record a direct decision.</p><Field label="Decision"><select name="status" className={control}><option value="APPROVED">Approve</option><option value="REJECTED">Reject</option></select></Field><button disabled={action.busy} className={secondary}>Record direct decision</button></form>}
  </article>)}
  </Card></div></div>;
}
