'use client';

import { useEffect, useMemo, useState } from 'react';
import { EarlyPayPolicy, EarlyPayRequest, getEarlyPayPolicy, getEarlyPayRequests, reviewEarlyPayRequest, updateEarlyPayPolicy } from '../../lib/api';

const money = (n:number) => new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(n||0);
const badge = (s:string) => ({PAYMENT_FAILED:'bg-red-50 text-red-700',PENDING:'bg-amber-50 text-amber-700',APPROVED:'bg-blue-50 text-blue-700',PROCESSING:'bg-violet-50 text-violet-700',PAID:'bg-emerald-50 text-emerald-700',RECOVERED:'bg-slate-100 text-slate-700',REJECTED:'bg-red-50 text-red-700'}[s] ?? 'bg-slate-100 text-slate-700');

export default function EarlyPayPage(){
  const [requests,setRequests]=useState<EarlyPayRequest[]>([]); const [policy,setPolicy]=useState<EarlyPayPolicy|null>(null);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  async function load(){ try{setLoading(true);setError(''); const [r,p]=await Promise.all([getEarlyPayRequests(),getEarlyPayPolicy()]);setRequests(r);setPolicy(p);}catch(e){setError(e instanceof Error?e.message:'Failed to load Early Pay');}finally{setLoading(false);} }
  useEffect(()=>{load();},[]);
  const totals=useMemo(()=>({pending:requests.filter(r=>r.status==='PENDING').length,paid:requests.filter(r=>['PAID','RECOVERED'].includes(r.status)).reduce((s,r)=>s+r.requestedAmount,0),fees:requests.filter(r=>['PAID','RECOVERED'].includes(r.status)).reduce((s,r)=>s+r.serviceFee+r.transferFee+r.instantFee,0),recovery:requests.filter(r=>r.status==='PAID').reduce((s,r)=>s+r.totalPayrollRecovery,0)}),[requests]);
  async function review(id:string,status:'APPROVED'|'REJECTED'){try{await reviewEarlyPayRequest(id,status,status==='REJECTED'?'Rejected by payroll review':undefined);await load();}catch(e){setError(e instanceof Error?e.message:'Review failed');}}

  async function savePolicy(){if(!policy)return;try{setSaving(true);setPolicy(await updateEarlyPayPolicy(policy));}catch(e){setError(e instanceof Error?e.message:'Policy update failed');}finally{setSaving(false);}}
  if(loading)return <main className="p-6 text-sm text-slate-500">Loading Early Pay…</main>;
  return <main className="space-y-6 p-4 md:p-7">
    <section className="rounded-3xl bg-slate-950 p-6 text-white shadow-sm md:p-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-300">Earned Wage Access</p><h1 className="mt-2 text-3xl font-bold">Early Pay</h1><p className="mt-3 text-sm leading-6 text-slate-300">Employees access a controlled portion of estimated net pay already earned. DeluxHR reserves for estimated PAYE, UIF and protected deductions before calculating availability, then reconciles paid advances through payroll.</p></div></section>
    {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <section className="grid gap-4 md:grid-cols-4">{[['Pending review',totals.pending],['Paid this cycle',money(totals.paid)],['Fees collected',money(totals.fees)],['Awaiting payroll recovery',money(totals.recovery)]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{l}</p><p className="mt-2 text-2xl font-bold text-slate-950">{v}</p></div>)}</section>
    {policy&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold text-slate-950">Early Pay policy</h2><p className="text-sm text-slate-500">Employer-controlled eligibility, reserves, limits and fees.</p></div><button onClick={savePolicy} disabled={saving} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">{saving?'Saving…':'Save policy'}</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Field label="Minimum working days" value={policy.minimumQualifyingDays} onChange={v=>setPolicy({...policy,minimumQualifyingDays:v})}/><Field label="Accessible net pay %" value={policy.accessibleNetPercentage} onChange={v=>setPolicy({...policy,accessibleNetPercentage:v})}/><Field label="Minimum request" value={policy.minimumRequestAmount} onChange={v=>setPolicy({...policy,minimumRequestAmount:v})}/><Field label="Maximum request" value={policy.maximumRequestAmount} onChange={v=>setPolicy({...policy,maximumRequestAmount:v})}/><Field label="Requests / pay cycle" value={policy.maximumRequestsPerPeriod} onChange={v=>setPolicy({...policy,maximumRequestsPerPeriod:v})}/><Field label="Payday" value={policy.paydayDay} onChange={v=>setPolicy({...policy,paydayDay:v})}/><Field label="Cutoff days" value={policy.paydayCutoffDays} onChange={v=>setPolicy({...policy,paydayCutoffDays:v})}/><Field label="PAYE reserve %" value={policy.estimatedPayeReserveRate} onChange={v=>setPolicy({...policy,estimatedPayeReserveRate:v})}/><Field label="UIF reserve %" value={policy.estimatedUifReserveRate} onChange={v=>setPolicy({...policy,estimatedUifReserveRate:v})}/><Field label="Protected deductions %" value={policy.protectedDeductionRate} onChange={v=>setPolicy({...policy,protectedDeductionRate:v})}/><Field label="Transaction fee %" value={policy.transactionFeePercentage} onChange={v=>setPolicy({...policy,transactionFeePercentage:v})}/><Field label="Standard transfer fee" value={policy.standardTransferFee} onChange={v=>setPolicy({...policy,standardTransferFee:v})}/><Field label="Instant transfer fee" value={policy.instantTransferFee} onChange={v=>setPolicy({...policy,instantTransferFee:v})}/>
    </div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800"><b>Tax safeguard:</b> PAYE/UIF percentages here are conservative eligibility reserves, not the final statutory calculation. Production payroll must use the authoritative tax engine.</p></section>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-950">Early Pay requests</h2><p className="text-sm text-slate-500">Review requests here. Platform treasury handles funding, payout approval and bank-result confirmation.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr>{['Employee','Earned net','Requested','Fees','Payroll recovery','Speed','Status','Action'].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{requests.map(r=><tr key={r.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{r.employee?`${r.employee.firstName} ${r.employee.lastName}`:r.employeeId}</p><p className="text-xs text-slate-400">{r.qualifyingDays} qualifying days</p></td><td className="px-5 py-4">{money(r.estimatedNetEarned)}</td><td className="px-5 py-4 font-semibold">{money(r.requestedAmount)}</td><td className="px-5 py-4">{money(r.serviceFee+r.transferFee+r.instantFee)}</td><td className="px-5 py-4 font-semibold">{money(r.totalPayrollRecovery)}</td><td className="px-5 py-4">{r.transferType}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${badge(r.status)}`}>{r.status}</span>{r.paymentReference?.startsWith('SIM-')&&<p className="mt-1 text-xs text-amber-700">Legacy simulated payment</p>}</td><td className="px-5 py-4"><div className="flex gap-2">{r.status==='PENDING'&&<><button onClick={()=>review(r.id,'APPROVED')} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">Approve</button><button onClick={()=>review(r.id,'REJECTED')} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold">Reject</button></>}{r.status==='APPROVED'&&<span className="text-xs text-slate-500">Await platform treasury</span>}{r.status==='PROCESSING'&&<span className="text-xs text-slate-500">Treasury processing</span>}{r.status==='PAYMENT_FAILED'&&<span className="text-xs text-amber-700">Treasury recovery needed</span>}{r.status==='PAID'&&<span className="text-xs text-slate-500">Await payroll</span>}{r.status==='RECOVERED'&&<span className="text-xs font-semibold text-emerald-700">Recovered</span>}</div></td></tr>)}{!requests.length&&<tr><td colSpan={8} className="px-5 py-10 text-center text-slate-400">No Early Pay requests yet. Employees can request through WhatsApp.</td></tr>}</tbody></table></div></section>
    <section className="grid gap-4 md:grid-cols-5">{['Verified work','Estimated net earned pay','Employee request','Employer approval & payment','Payroll recovery'].map((x,i)=><div key={x} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-indigo-600">0{i+1}</p><p className="mt-2 text-sm font-semibold text-slate-900">{x}</p></div>)}</section>
  </main>;
}
function Field({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="text-xs font-semibold text-slate-600">{label}<input type="number" value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-indigo-400"/></label>}
