'use client';
import Link from 'next/link';
import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import { usePathname } from 'next/navigation';
import { getWorkspaceAccess, routeAllowed, routeRoot, type WorkspaceAccess } from '../../lib/workspace-access';
const Context=createContext<{access:WorkspaceAccess|null;reload:()=>Promise<void>}>({access:null,reload:async()=>{}});
export const useWorkspaceAccess=()=>useContext(Context);
export function WorkspaceAccessProvider({children}:{children:ReactNode}){const [access,setAccess]=useState<WorkspaceAccess|null>(null),[error,setError]=useState('');async function reload(){try{setAccess(await getWorkspaceAccess());setError('');}catch(e){setAccess(null);setError(e instanceof Error?e.message:'Access could not be checked.');throw e;}}useEffect(()=>{void reload().catch(()=>{});const onFocus=()=>void reload().catch(()=>{});window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus);},[]);return <Context.Provider value={{access,reload}}>{error?<div className="m-5 rounded border border-red-200 p-5"><p role="alert">{error}</p><button onClick={()=>void reload().catch(()=>{})}>Retry access check</button></div>:children}</Context.Provider>;}
export function WorkspaceBoundary({children}:{children:ReactNode}){const {access,reload}=useWorkspaceAccess(),path=usePathname(),root=routeRoot(path);if(!access)return <p className="p-6 text-sm text-slate-500">Checking available services…</p>;if(root&&!routeAllowed(access,root))return <section className="rounded-2xl border bg-white p-6 space-y-4"><h1 className="text-xl font-semibold">This page is unavailable for your account</h1><p>Your company service settings or current permissions do not allow this page.</p>{access.role==='COMPANY_ADMIN'?<Link href="/company-services" className="text-indigo-600 underline">Review company services</Link>:<p className="text-sm">Ask your company administrator to review your access.</p>}<div><button onClick={()=>void reload().catch(()=>{})} className="text-indigo-600 underline">Refresh access</button></div></section>;return <>{children}</>;}
