"use client";
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Card, Field, Notice, control, button, secondary, useAction, text } from '@/components/leave/ui';
import { PlatformPageTitle, PlatformUsers, PlatformAuditView, UsageCards } from '@/components/platform-admin/common';
import * as api from '@/lib/platform-api';
const tabs=['Overview','Subscription & features','Users','Readiness','Support','Audit'];
export default function Page(){const {id}=useParams<{id:string}>();const [org,setOrg]=useState<api.PlatformOrganization|null>(null),[tab,setTab]=useState(tabs[0]);const action=useAction();useEffect(()=>{setOrg(null);void action.run(async()=>{setOrg(await api.getPlatformOrganization(id));});},[id]);return <><PlatformPageTitle title={org?.name??'Company administration'} text="Manage company status, subscription, accounts and support access."/><Notice error={action.error} message={action.message}/>{org&&<><nav className="flex flex-wrap gap-2 mb-5">{tabs.map(t=><button key={t} className={tab===t?button:secondary} onClick={()=>setTab(t)}>{t}</button>)}</nav>{tab==='Overview'&&<Overview org={org} changed={setOrg}/>} {tab==='Subscription & features'&&<Entitlements org={org}/>} {tab==='Users'&&<PlatformUsers organizationId={id}/>} {tab==='Readiness'&&<Readiness id={id}/>} {tab==='Support'&&<Support id={id}/>} {tab==='Audit'&&<PlatformAuditView organizationId={id}/>}</>}</>;}
function Overview({org,changed}:{org:api.PlatformOrganization;changed:(o:api.PlatformOrganization)=>void}){const [usage,setUsage]=useState<api.PlatformUsage|null>(null);const action=useAction();useEffect(()=>{void action.run(async()=>{setUsage(await api.getPlatformUsage(org.id));});},[org.id]);return <><Notice error={action.error} message={action.message}/>{usage&&<UsageCards usage={usage}/>}<Card title="Company profile"><p>Status: <strong>{org.status}</strong></p><p>{org.legalName??org.name}</p><p>{org.email} {org.phoneNumber}</p><p>Registration: {org.registrationNumber??'Not supplied'}</p><p>Created: {new Date(org.createdAt).toLocaleString()}</p><p>{org._count.employees} employees · {org._count.users} users · {org._count.departments} departments</p></Card><Card title="Company status">{api.tenantTransitions[org.status].length?<form className="space-y-4" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action.run(async()=>{const status=text(d,'status') as api.OrganizationStatus;if(!window.confirm(`Change ${org.name} to ${status}?${status==='REJECTED'?' Rejection is terminal.':''}`))return false;await api.changeTenantStatus(org.id,status,text(d,'reason'));try{changed(await api.getPlatformOrganization(org.id));}catch{throw new Error('Company status saved, but refresh failed. Reload before changing status again.');}},'Company status updated.');}}><Field label="New status *"><select className={control} name="status">{api.tenantTransitions[org.status].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Reason *"><textarea className={control} name="reason" required maxLength={1000}/></Field><p className="text-sm">Pending companies must pass the readiness checklist before activation. Suspension blocks company access.</p><button className={button} disabled={action.busy}>Change status</button></form>:<p>This company has no available status transitions.</p>}</Card></>;}
function featureName(value:string){return ({CORE_HR:'Core HR',LEAVE:'Leave',ATTENDANCE:'Attendance',TIMESHEETS:'Timesheets',PAYROLL:'Payroll',PAYSLIPS:'Payslips',WHATSAPP:'WhatsApp',EARLY_PAY:'Early Pay',WORKFORCE_INSIGHTS:'Workforce insights',EXECUTIVE_DASHBOARD:'Executive dashboard'} as Record<string,string>)[value]??value;}
function Entitlements({org}:{org:api.PlatformOrganization}){
 const [packages,setPackages]=useState<api.PlatformPackage[]>([]),[features,setFeatures]=useState<api.TenantFeature[]>([]),[subscription,setSubscription]=useState<api.PlatformSubscription|null>(null),[packageId,setPackageId]=useState(''),[loaded,setLoaded]=useState(false);
 const action=useAction();
 const load=async()=>{const [p,f,s]=await Promise.all([api.getPlatformPackages(),api.getTenantFeatures(org.id),api.getTenantSubscription(org.id)]);setPackages(p);setFeatures(f);setSubscription(s);setPackageId(s?.packageId??'');setLoaded(true);};
 useEffect(()=>{void action.run(load);},[org.id]);
 const activePackages=packages,selected=activePackages.find(p=>p.id===packageId);
 return <><Notice error={action.error} message={action.message}/>
 <Card title="Core HR included"><p>Core HR is available by default. Choose an optional edition to add services.</p></Card>
 {!loaded?<Card title="Load subscription"><p>{action.busy?'Loading package and access settings…':'Settings could not be loaded.'}</p><button className={secondary} disabled={action.busy} onClick={()=>void action.run(load)}>Retry loading</button></Card>:<>
 <Card title="Optional services"><p>{subscription?`Current package: ${subscription.package.name} · ${subscription.status}`:'Core HR only — no additional edition selected.'}</p>

 {!activePackages.length&&<p className="mt-3">No active packages are available. <a className="underline" href="/platform-admin/packages">Create or enable a package</a>, then return here and refresh.</p>}
 <form key={subscription?.id??'new'} className="space-y-4 mt-4" onSubmit={e=>{e.preventDefault();if(action.busy)return;const d=new FormData(e.currentTarget);void action.run(async()=>{
 const status=text(d,'status') as api.PlatformSubscription['status'],end=text(d,'endsAt'),reason=text(d,'reason');
 if(!selected)throw new Error('Choose an active package before saving.');
 if(reason.length<8)throw new Error('Enter a reason of at least 8 characters, for example: Add payroll for this company.');
 if(!['ACTIVE','PAUSED','CANCELLED'].includes(status))throw new Error('Choose a valid subscription status.');
 const date=end?new Date(end):null;if(date&&Number.isNaN(date.getTime()))throw new Error('Enter a valid expiry date and time.');
 const endsAt=date?.toISOString();if(status==='ACTIVE'&&date&&date<=new Date())throw new Error('Choose a future expiry for an Active subscription, or leave expiry blank.');
 if(!window.confirm(`Apply ${selected.name} (${status})? This replaces existing feature settings with: ${selected.features.map(featureName).join(', ')||'no services'}.`))return false;
 const saved=await api.setTenantSubscription(org.id,{packageId:selected.id,status,endsAt,reason});setSubscription(saved);try{await load();}catch{setLoaded(false);throw new Error('Subscription saved, but access settings could not be refreshed. Retry loading before making another change.');}
 },'Package and subscription saved. Refresh the company onboarding readiness checklist.');}}>
 <Field label="Edition *"><select className={control} name="packageId" required value={packageId} onChange={e=>setPackageId(e.target.value)}><option value="">Choose additional services</option>{activePackages.map(p=><option key={p.id} value={p.id}>{p.name} ({p.code})</option>)}</select></Field>
 {selected&&<div className="rounded border p-4 space-y-2"><strong>Included in {selected.name}</strong>{selected.description&&<p>{selected.description}</p>}<p>{selected.features.map(featureName).join(', ')||'No services included'}</p><p className="text-sm">Employee limit: {selected.employeeLimit??'No package limit'}</p>{!selected.features.includes('CORE_HR')&&<p className="text-sm text-amber-700">This package does not include Core HR. Core HR must be enabled before company activation.</p>}</div>}
 <details><summary className="cursor-pointer text-sm font-medium">Status & expiry</summary><div className="space-y-3 mt-3"><Field label="Subscription status *"><select className={control} name="status" required defaultValue={subscription?.status??'ACTIVE'}><option value="ACTIVE">Active — allow subscribed services</option><option value="PAUSED">Paused — temporarily block services</option><option value="CANCELLED">Cancelled — block services</option></select></Field>
 <Field label="Expiry (optional)"><input className={control} type="datetime-local" name="endsAt" defaultValue={subscription?.endsAt?localDate(subscription.endsAt):''}/></Field><p className="text-sm">Blank means no expiry.</p></div></details>
 <Field label="Reason for this change *"><textarea className={control} name="reason" required minLength={8} maxLength={500} placeholder="Example: Add payroll for this company"/></Field>
 <p className="text-sm">Changing edition replaces optional services; Core HR remains included.</p>
 <button className={button} disabled={action.busy||!activePackages.length}>{action.busy?'Saving…':subscription?'Update company subscription':'Add selected edition'}</button>
 </form></Card>
 <Card title="Service access"><p className="mb-4">Selected services require their setup steps to be completed.</p>{!subscription&&<p className="mb-4">Core HR is included. Add services using an edition above.</p>}
 <div className="grid gap-3 sm:grid-cols-2">{features.filter(f => f.enabled).map(f=><div key={f.feature} className="border rounded p-3"><strong>{featureName(f.feature)}</strong><p className="text-sm">{f.effectiveEnabled?'Selected':'Subscription paused or expired'}</p>{f.enabled&&!f.effectiveEnabled&&<p className="text-sm">Check whether the subscription is active and has not expired.</p>}</div>)}</div>
 <details className="mt-5 border rounded p-4"><summary className="cursor-pointer font-semibold">Advanced: change individual services</summary><p className="my-3 text-sm">Individual changes are replaced when the edition changes.</p>
 <div className="space-y-4">{features.map(f=>{const payroll=features.some(x=>x.feature==='PAYROLL'&&x.enabled);const blockedReason=!subscription?'Select an edition to configure additional services.':f.feature==='CORE_HR'?'Core HR is always included.':f.enabled&&f.feature==='PAYROLL'&&features.some(x=>['PAYSLIPS','EARLY_PAY'].includes(x.feature)&&x.enabled)?'Disable Payslips and Early Pay before disabling Payroll.':!f.enabled&&['PAYSLIPS','EARLY_PAY'].includes(f.feature)&&!payroll?'Enable Payroll before enabling this service.':null;
 return <form key={f.feature} className="border rounded p-4 space-y-2" onSubmit={e=>{e.preventDefault();if(action.busy)return;const d=new FormData(e.currentTarget);void action.run(async()=>{const reason=text(d,'reason');if(blockedReason)throw new Error(blockedReason);if(reason.length<3)throw new Error('Enter a reason of at least 3 characters.');if(!window.confirm(`${f.enabled?'Disable':'Enable'} ${featureName(f.feature)}?`))return false;await api.setTenantFeature(org.id,f.feature,!f.enabled,reason);try{setFeatures(await api.getTenantFeatures(org.id));}catch{setLoaded(false);throw new Error('Service saved, but refresh failed. Retry loading before changing it again.');}},'Company service updated.');}}><strong>{featureName(f.feature)}</strong>{blockedReason?<p className="text-sm">{blockedReason}</p>:<><Field label="Reason for service change *"><input className={control} name="reason" placeholder="Example: Add attendance for this company" required minLength={3} maxLength={500}/></Field><button className={secondary} disabled={action.busy}>{f.enabled?'Disable service':'Enable service'}</button></>}</form>;})}</div></details></Card>
 </>}</>;
}
function localDate(value:string){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function Readiness({id}:{id:string}){const [ready,setReady]=useState<api.TenantReadiness|null>(null),[onboarding,setOnboarding]=useState<api.TenantOnboarding|null>(null);const action=useAction();const load=async()=>{const [r,o]=await Promise.all([api.getTenantReadiness(id),api.getTenantOnboarding(id)]);setReady(r);setOnboarding(o);};useEffect(()=>{void action.run(load);},[id]);return <><Notice error={action.error} message={action.message}/><Card title="Go-live readiness"><button className={secondary} disabled={action.busy} onClick={()=>void action.run(load)}>Refresh checklist</button>{ready&&<><p className="my-4">{ready.ready?'Ready for activation':'Setup incomplete'} · {ready.progress.completedSteps}/{ready.progress.totalSteps} steps ({ready.progress.percentage}%)</p><ul className="space-y-2">{ready.checklist.filter(c => c.key !== 'package').map(c=><li key={c.key}>{c.ready?'✓':'Pending'} · {c.key.replaceAll('_',' ')} · {c.required?'Required':'Optional'}</li>)}</ul><div className="mt-4">{Object.entries(ready.counts).map(([k,v])=><p key={k}>{k}: {v}</p>)}</div></>}{onboarding&&<p className="mt-4">Onboarding: {onboarding.onboarding?.status??'Not configured'}</p>}<p className="text-sm mt-4">Company setup editing belongs to the onboarding workflow. This view checks the API readiness gate.</p></Card></>;}
function Support({id}:{id:string}){const [users,setUsers]=useState<api.PlatformUser[]>([]),[session,setSession]=useState(''),[preview,setPreview]=useState<api.SupportPreview|null>(null);const action=useAction();useEffect(()=>{setSession('');setPreview(null);void action.run(async()=>{setUsers(await api.getPlatformUsers(id));});},[id]);const inspect=async()=>{setPreview(null);const p=await api.previewSupportSession(session.trim());if(p.organization.id!==id)throw new Error('This session belongs to another company. Open that company to preview it.');setPreview(p);};return <><Notice error={action.error} message={action.message}/><Card title="Read-only support preview"><p className="mb-4">Support sessions expose a limited company preview. Your platform identity remains active. Starting a session revokes your previous sessions for this company.</p><form className="space-y-4" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action.run(async()=>{const s=await api.startSupportSession(id,text(d,'targetUserId'),text(d,'reason'));setSession(s.id);setPreview(null);},'Support session created. Use Preview to inspect it.');}}><Field label="Active company administrator *"><select className={control} required name="targetUserId"><option value="">Select administrator</option>{users.filter(u=>u.isActive&&u.role==='COMPANY_ADMIN').map(u=><option key={u.id} value={u.id}>{u.fullName} · {u.email}</option>)}</select></Field><Field label="Support reason *"><textarea className={control} name="reason" required minLength={12} maxLength={500}/></Field><button className={button} disabled={action.busy}>Start support session</button></form><div className="space-y-3 mt-6"><Field label="Session ID"><input className={control} value={session} onChange={e=>{setSession(e.target.value);setPreview(null);}} placeholder="Current or known session ID"/></Field><button className={secondary} disabled={!session.trim()||action.busy} onClick={()=>void action.run(inspect)}>Preview</button> <button className={secondary} disabled={!session.trim()||action.busy} onClick={()=>void action.run(async()=>{if(!window.confirm('Revoke this support session?'))return false;await api.revokeSupportSession(session.trim());setPreview(null);setSession('');},'Support session revoked.')}>Revoke</button></div></Card>{preview&&<Card title="READ-ONLY PREVIEW"><p>{preview.organization.name} · {preview.organization.status}</p><p>Target: {preview.target.email}</p><p>Expires: {new Date(preview.session.expiresAt).toLocaleString()}</p><p>Onboarding: {preview.onboarding?.status??'Not configured'}</p><UsageCards usage={preview.usage}/><p className="mt-4">Feature flags: {preview.features.filter(f=>f.enabled).map(f=>f.feature).join(', ')||'None'}</p><p className="text-sm">These are stored flags; subscription gating can affect effective access.</p></Card>}</>;}
